<?php

namespace Database\Seeders;

//use Illuminate\Database\Console\Seeds\WithoutModelEvents;
//use App\Models\Abstracts;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AbstractTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $abstracts = [
            [
                'applicant_name' => 'Axmedov Oybek Saporboyevich',
                'dissertation_topic' => '“Ingliz va o`zbek tillarida soliq-bojxona terminlarining lingvistik tahlili va tarjima muammolari"',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2011,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/08/ahmedov.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Djumabayeva Jamila Sharipovna',
                'dissertation_topic' => 'O`zbek va ingliz tillarida leksik hamda stilistik graduonimiya',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2016,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/01/avtoref_jumabayeva.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Djumanova Dilbar Rahimovna',
                'dissertation_topic' => 'Til aloqasi sharoitida so`zning fonologik modeli',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2016,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/01/avtoref_jumanova.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Kamilova Saodat Ergashevna',
                'dissertation_topic' => 'XX asr oxiri – 21-asr boshlari rus va oʻzbek adabiyotida qissa janri poetikasining rivojlanishi',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2016,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/01/avtoref_kamilovas.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Nasirov Abdurahim Abdimutalipovich',
                'dissertation_topic' => 'Fransuz, o`zbek va rus tillaridagi proverbial frazeologizmlarning semantik-stilistik va milliy-madaniy xususiyatlar',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2016,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/01/avtoref_nosirov.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Paluanova Halifa Dariboevna',
                'dissertation_topic' => 'Ingliz, o`zbek, rus va qoraqalpoq tillarida ekologik terminlaring derivasiong`semantik prinsiplari',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2016,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/01/avtoref_paluanova.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xalliyeva Gulnoz Iskandarovna',
                'dissertation_topic' => 'XX asr rus sharqshunosligida o`zbek mumtoz adabiyoti tadqiq',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2016,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/01/avtoref_hallieva.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Baxronova Dilrabo Keldiyorovna',
                'dissertation_topic' => 'Antropozoomorfizmlarning semantik va lingvokulturologik xususiyatlari (o`zbek va ispan tillari materialida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2018/08/baxronova.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Jo`rayeva Malohat Muhamadovna',
                'dissertation_topic' => 'Fransuz va o`zbek ertaklarida modallik kategoriyasining lingvokognitiv, milliy-madaniy xususiyatlari',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2018/02/jurayevam.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Qodirbekova Durdona Xikmatullaevna',
                'dissertation_topic' => 'Inglizcha-o`zbekcha axborot-kommunikatsiya exnologiyalari terminologiyasi va uning leksikografik xususiyatlar',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Kdirbayeva Gulzira Qurbonboevna',
                'dissertation_topic' => 'Man” – “adam” konseptosferasi birliklarining lingvomadaniy va lingvokognitiv xususiyatlari (ingliz va qoraqalpoq tillari misolida',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2018/02/kdirbayeva.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Samigova Xushnuda Botirovna',
                'dissertation_topic' => 'Ingliz va o`zbek nutq madaniyatining ritoric aspektining qiyosiy tadqiq',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/10/samigova_h.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Sharipova Aziza Abdumanapovna',
                'dissertation_topic' => 'Stilistik sinonimlar tarjimasining lingvokul-turologik xususiyatlari (ingliz va o`zbek tillari materiallari asosida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2018/02/sharipova_a.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Shirinova Raima Xakimovna',
                'dissertation_topic' => 'Olam milliy manzarasining badiiy tarjimada qayta yaratilishi',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/09/shirinova_r.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Teshaboyeva Ziyodaxon Qodirovna',
                'dissertation_topic' => 'Boburnoma”ning inglizcha tarjimalaridagi frazeologik birliklar va tahrir milliy-madaniy xususiyatlar',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2018/02/teshaboyeva.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Tuxtaxodjayeva Nargiza Akmalovna',
                'dissertation_topic' => 'Badiiy tarjimada lingvo-kulturemalarning ifodalanishi (ingliz va o`zbek tillari misolida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/10/tuhtahodjayeva_n.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xolmurodova Leyla Eshquvatovna',
                'dissertation_topic' => 'Ingliz va fransuz tillaridagi obrazli va motivlashgan frazeologizmlarning tematik-ideografik talqini (lingvomadaniy aspekt)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2018/02/holmuradova.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xudjayeva Ra`no Mutalibjonovna',
                'dissertation_topic' => 'Ingliz va o`zbek tillaridagi genetik bog`lanmagan leksik omonimlarning miqdori va leksikografik talqin',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2017/10/hudjayeva_r.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Yo`ldoshev Ulug`bek Ravshanbekovich',
                'dissertation_topic' => 'Xajviy matnlar tarjimasining lingvostilistik va lingvokulturorlogik xususiyatlari” (ingliz tiliga tarjima qilingan o`zbek xalq latifalari misolida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2018/02/yuldoshev.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Yuldashev Akmal Gulamjanovich',
                'dissertation_topic' => 'Idiomatik qo`shma so`zlarning lingvokognitiv aspekti” (ingliz va o`zbek tillari misolida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2017 ,
                'file_url' => 'http://tsuos.uz/wp-content/uploads/2018/02/yuldashev_a.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Djafarova Dildora Ilxomovna',
                'dissertation_topic' => 'Fransuz va o`zbek tillarida leksik motivlashuvning milliy-madaniy xususiyatlari',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Qosimova Ra`no Raxmatulloyevna',
                'dissertation_topic' => 'O`zbek to`y va motam marosim folklor matnlarining inglizcha tarjimasida etnografizmlarning namunalari',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Mo`minova Aziza Arslanovna',
                'dissertation_topic' => 'Fransuz, o`zbek va rus tillarida undashni ifodalovchi til birliklarining lingvomadaniy xususiyatlari',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Qosimova Nafisa Farhodovna',
                'dissertation_topic' => 'Lisoniy belgi asimmetriyasi va uning so`roq gap tarjimasida voqelanishi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Sapayeva Feruza Davlatovna',
                'dissertation_topic' => 'Maxtumquli she`rlari o`zbekcha tarjima qiyosiy tahlil',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Sayfullaev Anvar Islomovich',
                'dissertation_topic' => 'Preposition va kwmakchilarining nominative-sintagmativ mavkei va tipologik strukturaviy makomi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Toirova Nargiza Isakovna',
                'dissertation_topic' => 'Badiiy adabiyotda koʻzgu va surat ramzlarining gʻoyaviy-estetik asarlari (Omon Muxtor va Oskar Uayld asarlari asosidai',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xajiyeva Feruza Melsovna',
                'dissertation_topic' => 'Biografik roman janri xususiyatlari (I.Stoun, M.Qoriev va N.Normatov asarlari qiyosida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xodjayeva Dilafro`z Izatilloyevna',
                'dissertation_topic' => 'Tilshunoslik terminlarining leksikografik tahlili (ingliz, rus va o`zbek tillari izohli lug`atlari materiallari misolida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xoliqov Bahodir Aliqulovich',
                'dissertation_topic' => 'Detektiv romanlarda voqelikning badiiy talqinini tizimli modellashtirish (Mario Pyuzoning “The Godfather” va Tohir Malikning “Shaytanat”)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xoshimova Dildora Madaminovna',
                'dissertation_topic' => 'Boburnoma” matnidagi tasviriy tadqiqotning ingliz tiliga tarjimalari tadqiq',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xoshimxo`jayeva Mohirux Muzaffarovna',
                'dissertation_topic' => 'Olamning lisoniy tasvirida fitonimlar (ingliz, rus va o`zbek tillari misolida',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2018 ,
                'file_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Asqarova Shaxnoza Kamolidinovna',
                'dissertation_topic' => 'Ingliz va o`zbek tillarida takrorning lingvistik xususiyatlari',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2019 ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%90%D1%81%D2%9B%D0%B0%D1%80%D0%BE%D0%B2%D0%B0-%D0%A8%D0%B0%D1%85%D0%BD%D0%BE%D0%B7%D0%B0-%D0%9A%D0%B0%D0%BC%D0%BE%D0%BB%D0%B8%D0%B4%D0%B8%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xodjayeva Nilufar Bekmuratovna',
                'dissertation_topic' => 'Premchand asarlari o`zbekcha tarjimalarining leksik-stilistik xususiyatlari',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2019 ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%A5%D0%BE%D0%B4%D0%B6%D0%B0%D0%B5%D0%B2%D0%B0-%D0%9D%D0%B8%D0%BB%D1%83%D1%84%D0%B0%D1%80-%D0%91%D0%B5%D0%BA%D0%BC%D1%83%D1%80%D0%B0%D1%82%D0%BE%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Raxmatjonova Kamola Abdumutal kizi',
                'dissertation_topic' => 'Hindiy va o`zbek tillarida son va kelishik grammatik katyegoriyalarining chog`ishtirma-tipologik tadqiqi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2020 ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%A0%D0%B0%D1%85%D0%BC%D0%B0%D1%82%D0%B6%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0-%D0%9A%D0%B0%D0%BC%D0%BE%D0%BB%D0%B0-%D0%90%D0%B1%D0%B4%D1%83%D0%BC%D1%83%D1%82%D0%B0%D0%BB-%D0%BA%D0%B8%D0%B7%D0%B8.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Shamsiyeva Shohista Qudratullayevna',
                'dissertation_topic' => 'Xitoy va o`zbek tillaridagi maishiy evfemizmlarning lingvomadaniy tadqiqi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2020 ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%A8%D0%B0%D0%BC%D1%81%D0%B8%D0%B5%D0%B2%D0%B0-%D0%A8%D0%BE%D2%B3%D0%B8%D1%81%D1%82%D0%B0-%D2%9A%D1%83%D0%B4%D1%80%D0%B0%D1%82%D1%83%D0%BB%D0%BB%D0%B0%D0%B5%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Turapova Nargiza Axmedovna',
                'dissertation_topic' => 'Yapon va o`zbek tillari somatik frazeologizmlarining chog`ishtirma tahlili (lingvomadaniy aspyekt)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2020 ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%A2%D1%83%D1%80%D0%B0%D0%BF%D0%BE%D0%B2%D0%B0-%D0%9D%D0%B0%D1%80%D0%B3%D0%B8%D0%B7%D0%B0-%D0%90%D1%85%D0%BC%D0%B5%D0%B4%D0%BE%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Zikrullayeva Xusniya Baxtiyorovna',
                'dissertation_topic' => 'Ingliz, turk va o`zbyek ilmiy-tyexnikaviy tarjimada lyeksik-syemantik transformasiyalar',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2020 ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%97%D0%B8%D0%BA%D1%80%D1%83%D0%BB%D0%BB%D0%B0%D0%B5%D0%B2%D0%B0-%D0%A5%D1%83%D1%81%D0%BD%D0%B8%D1%8F-%D0%91%D0%B0%D1%85%D1%82%D0%B8%D1%91%D1%80%D0%BE%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Ismatullayeva Nargiza Rasuljanovna',
                'dissertation_topic' => 'Xitoy va o`zbek tillarida lakunalarning voqelanishi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2021  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%98%D1%81%D0%BC%D0%B0%D1%82%D1%83%D0%BB%D0%BB%D0%B0%D0%B5%D0%B2%D0%B0-%D0%9D%D0%B0%D1%80%D0%B3%D0%B8%D0%B7%D0%B0-%D0%A0%D0%B0%D1%81%D1%83%D0%BB%D0%B6%D0%B0%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Saidakbarova Saodat Parxadjanovna',
                'dissertation_topic' => 'Ingliz va o`zbek tillarida gastronomik frazyeologizmlarning lingvomadaniy xususiyatlari',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2021  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%A1%D0%B0%D0%B8%D0%B4%D0%B0%D0%BA%D0%B1%D0%B0%D1%80%D0%BE%D0%B2%D0%B0-%D0%A1%D0%B0%D0%BE%D0%B4%D0%B0%D1%82-%D0%9F%D0%B0%D1%80%D1%85%D0%B0%D0%B4%D0%B6%D0%B0%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Sharaxmetova Muxlisa Ansaritdinovna',
                'dissertation_topic' => 'Bobur urducha tarjimasida muallif uslubiga xos leksik-semantik ishlab chiqarishning ask etishi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2021  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%A8%D0%B0%D1%80%D0%B0%D1%85%D0%BC%D0%B5%D1%82%D0%BE%D0%B2%D0%B0-%D0%9C%D1%83%D1%85%D0%BB%D0%B8%D1%81%D0%B0-%D0%90%D0%BD%D1%81%D0%B0%D1%80%D0%B8%D1%82%D0%B4%D0%B8%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Xomidov Xayrullo Xudoyorovich',
                'dissertation_topic' => 'O`zbek qissa valarining roman turkcha tarjimalarida milliylik, badiiylik va lisoniy adekvatik masalalari',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2021  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/%D0%A5%D0%BE%D0%BC%D0%B8%D0%B4%D0%BE%D0%B2-%D0%A5%D0%B0%D0%B9%D1%80%D1%83%D0%BB%D0%BB%D0%BE-%D0%A5%D1%83%D0%B4%D0%BE%D1%91%D1%80%D0%BE%D0%B2%D0%B8%D1%87.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Abdullayeva Dilafruz Suratillayevna',
                'dissertation_topic' => 'Zamonaviy arab va o`zbek hiqoyalarida badiiy psixologizm (G`ada As-samman va Zulfiya Qurolboy qizi hikoyalari misolida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/14.-%D0%90%D0%B1%D0%B4%D1%83%D0%BB%D0%BB%D0%B0%D0%B5%D0%B2%D0%B0-%D0%94%D0%B8%D0%BB%D0%B0%D1%84%D1%80%D1%83%D0%B7-%D0%A1%D1%83%D1%80%D0%B0%D1%82%D0%B8%D0%BB%D0%BB%D0%B0%D0%B5%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Ashirbayeva Diloram Ravshanovna',
                'dissertation_topic' => 'Koreys va o`zbek diskursida murojaat birlik qiyosiy tadqiqi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2022/12/AVTOREFARAT.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Baxadirov Jaxangirmirzo Abdumajitovich',
                'dissertation_topic' => 'O`zbek va ingliz tillaridagi ijtimoiy reklamalarning lingvomadaniy tadqiqi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022  ,
                'file_url' => '',
//                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/5.-%D0%91%D0%B0%D1%85%D0%B0%D0%B4%D0%B8%D1%80%D0%BE%D0%B2-%D0%96%D0%B0%D1%85%D0%B0%D0%BD%D0%B3%D0%B8%D1%80%D0%BC%D0%B8%D1%80%D0%B7%D0%BE-%D0%90%D0%B1%D0%B4%D1%83%D0%BC%D0%B0%D0%B6%D0%B8%D1%82%D0%BE%D0%B2%D0%B8%D1%87.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Dilrabo Keldiyorovna Baxronova',
                'dissertation_topic' => 'Oʻzbek va ispan tillarida olam manzarasining lingvokognitiv kategoriyalanishi',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2022/05/O%CA%BBzbek-va-ispan-tillarida-olam-manzarasining-lingvokognitiv-kategoriyalanishi.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Mirzaxmedova Xulkar Vasilovna',
                'dissertation_topic' => 'Fors Va O`zbek Tillarida Termin Yasash Prinsplari Va muammolari',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/FORS-VA-OZBEK-TILLARIDA-TERMIN-YASASH-PRINSPLARI-VA-MUAMMOLARI.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Sadriddinzoda Safiya Shaxobiddinovna',
                'dissertation_topic' => 'Demonologik leksikaning semantik xususiyatlari va pragma-madaniy vositalarii (ingliz, o`zbek va rus adabiyoti asosida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2022/12/AVTOREFARAT-1.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Shamsiyev Barnoxon Baxromxodjayevna',
                'dissertation_topic' => 'Tarjima matni madaniyat transferi sifatida (Nasume Sosekining “Qalb” asari asosida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/15.-%D0%A8%D0%B0%D0%BC%D1%81%D0%B8%D0%B5%D0%B2%D0%B0-%D0%91%D0%B0%D1%80%D0%BD%D0%BE%D1%85%D0%BE%D0%BD-%D0%91%D0%B0%D1%85%D1%80%D0%BE%D0%BC%D1%85%D0%BE%D0%B4%D0%B6%D0%B0%D0%B5%D0%B2%D0%BD%D0%B0.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Umarova Mohira Azim qizi',
                'dissertation_topic' => 'XX asr o`zbek nasri namunalarining urdu tilidagi tarjimalarida milliy koloritning ifodalanishi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2022/11/Avtoreferat-1.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Yeon Sangheumning',
                'dissertation_topic' => 'Oʻzbek tilida modal maʼnoli koʻmakchi feʼllar va fayl koreys tilida ifodalanishi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022  ,
                'file_url' => 'https://tsuos.uz/wp-content/uploads/2018/02/O%CA%BBzbek-tilida-modal-ma%E2%80%99noli-ko%CA%BBmakchi-fe%E2%80%99llar-va-ularning-koreys-tilida-ifodalanishi.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'Jo Min Yong',
                'dissertation_topic' => 'O`zbek va koreys tillarida o`xshatishlarning lingvomadaniy tadqiqi',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023   ,
                'file_url' => 'https://drive.google.com/file/d/1rAzlmYKYpYw-pLox9EYH_KgjmJCDB7z8/view?usp=drive_link',
                'created_at' => now(),
                'updated_at' => now(),
            ],

//            Has file

            [
                'applicant_name' => 'КАХАROVA MOHIGUL YUSUFOVNA',
                'dissertation_topic' => 'INGLIZ VА O‘ZBEK BOLАLАR NАSRIDА O‘SMIRLАR RUHIYATI TАSVIRI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023   ,
                'file_url' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ИСАЕВА ШОИРА МАХАМАДОВНА',
                'dissertation_topic' => 'ЮСУФ ХОС ХОЖИБ АСАРИНИНГ ИНГЛИЗ ВА РУС ТИЛИДАГИ ТАРЖИМАЛАРИДА ЭКВИВАЛЕНТ БУЛМАГАН ЛЕКСИКАНИНГ ЛИНГВОМАДАНИЙ ЖИХАТЛАРИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'БАХРОНОВА ДИЛРАБО КЕЛДИЁРОВНА',
                'dissertation_topic' => 'УЗБЕК ВА ИСПАН ТИЛЛАРИДА ОЛАМ МАНЗАРАСИНИНГ ЛИНГВОКОГНИТИВ КАТЕГОРИЯЛАНИШИ',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'АБДУЛЛАЕВА МУХТАСАР АБДУЛЛА КИЗИ',
                'dissertation_topic' => 'УЗБЕК ВА АМЕРИКА БАДИИЙ АСАРЛАРИДА УМУМИНСОНИЙ кадриятлар ВАУЛАРНИНГ ТАРЖИМАДА КАЙТА ЯРАТИЛИШИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'АРУСТАМЯН ЯНА ЮРЬЕВНА',
                'dissertation_topic' => 'БАДИИЙ ТАРЖИМАНИНГ КОГНИТИВ-ПРАГМАТИК АСОСЛАРИ',
                'locale_id' => 1,
                'academic_degree' => 'DSc',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'XAMDAMOVA GULSHAN XAMROYEVNA',
                'dissertation_topic' => 'O‘ZBEK VA INGLIZ TILLARIDA SOMATIZMLAR ASOSIDA SHAKLLANGAN MAQOLLARNING KOGNITIV-SEMANTIK VA STRUKTUR XUSUSIYATLARI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'АСАДОВ МАҲМАДИЁР ТУРАЕВИЧ',
                'dissertation_topic' => 'АСАДОВ МАҲМАДИЁР ТУРАЕВИЧ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ДЎСТОВА СУРАЙЁ САВРОНОВНА',
                'dissertation_topic' => 'ҲАСАНМУРОД ЛАФФАСИЙНИНГ «ТАЗКИРАИ ШУАРО» АСАРИ ВА УНИНГ ҚИЁСИЙ-МАТНИЙ ТАДҚИҚИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2021,
                'file_url' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'BOZOROV ORIF CHAMANOVICH',
                'dissertation_topic' => 'EPISTOLYAR ROMANDA VOQELIKNI BADIIY TASVIRLASH IMKONIYATLARI VA QAHRAMON MUAMMOSI (IOGANN VOLFGANG FON GYOTENING “YOSH VERTERNING IZTIROBLARI” HAMDA IQBOL MIRZONING “BONU” ROMANLARI MISOLIDA)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'SAFAROVA ZILOLA TOLIBOVNA',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TARBIYA ROMANLARINING SPETSIFIK BELGILARI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'SHUKUROVA SABOHAT ODILOVNA',
                'dissertation_topic' => 'JON STEYNBEK VA NAZAR ESHONQUL ASARLARIDA SHAXS ERKI VA JAMIYAT MUNOSABATLARINING BADIIY-FALSAFIY TALQINI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'XAMDAMOVA GULSHAN XAMROYEVNA',
                'dissertation_topic' => 'O‘ZBEK VA INGLIZ TILLARIDA SOMATIZMLAR ASOSIDA SHAKLLANGAN MAQOLLARNING KOGNITIV-SEMANTIK VA STRUKTUR XUSUSIYATLARI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ХАБИБУЛЛАЕВА ФЕРУЗА КАЗИМЖАНОВНА',
                'dissertation_topic' => 'МИЛЛИЙ ЎЗИГА ХОСЛИКНИ ҚАЙТА ЯРАТИШ ТАРЖИМА АДЕКВАТЛИГИ МЕЗОНИ СИФАТИДА («Ўткан кунлар» романининг рус тилида таржималари мисолида)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2020,
                'file_url' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ШОДИЕВ ШАҲОБИДДИН ШАРОФИДДИНОВИЧ',
                'dissertation_topic' => 'ИНГЛИЗ УЙҒОНИШ ДАВРИ ВА ЖАДИДЛАР ТРАГИК АСАРЛАРИДАГИ СЕМАНТИК ИННОВАЦИЯЛАРНИНГ ЛИНГВО-ФАЛСАФИЙ АСПЕКТИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ШОДИЕВ ШАҲОБИДДИН ШАРОФИДДИНОВИЧ',
                'dissertation_topic' => 'ИНГЛИЗ УЙҒОНИШ ДАВРИ ВА ЖАДИДЛАР ТРАГИК АСАРЛАРИДАГИ СЕМАНТИК ИННОВАЦИЯЛАРНИНГ ЛИНГВО-ФАЛСАФИЙ АСПЕКТИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'БУМАТОВА АИДАХОН МЕРГАНОВНА',
                'dissertation_topic' => 'ШАРҚ ЛИРИК ЖАНРЛАРИНИНГ ИНГЛИЗЧА ТАРЖИМАЛАРИДА ШАКЛИЙ - СЕМАНТИК ВА ПОЭТИК УЙҒУНЛИК (ҒАЗАЛ ВА РУБОИЙ МИСОЛИДА)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2020,
                'file_url' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ИСМОИЛОВ ИЛЬЁС АБДУКАЮМОВИЧ',
                'dissertation_topic' => 'АЛИШЕР НАВОИЙ «САДДИ ИСКАНДАРИЙ» ДОСТОНИНИНГ ҚИЁСИЙ ТАҲЛИЛИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2019,
                'file_url' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'МУХДММАДИЕВА ДИЛАФРУЗ АХТАМОВА',
                'dissertation_topic' => '«БОБУРНОМА» ТУРКЧА ТАРЖИМАСИДА ПАРЕМИЯЛАРНИНГ КИЁСИЙ ТАДКИКИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2021,
                'file_url' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'КАХАROVA MOHIGUL YUSUFOVNA',
                'dissertation_topic' => 'INGLIZ VА O‘ZBEK BOLАLАR NАSRIDА O‘SMIRLАR RUHIYATI TАSVIRI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'НАСИРДИНОВА ЁРКИНОЙ АБДУМУХТАРОВНА',
                'dissertation_topic' => 'ЎЗБЕК ФОЛЬКЛОРИ ВА МУМТОЗ АДАБИЁТИ НАМУНАЛАРИ ФРАНЦУЗ ТИЛИДА (РЕМИ ДОР ТАРЖИМАЛАРИ АСOСИДА)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2019,
                'file_url' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'УМАРОВА МОҲИРА АЗИМ ҚИЗИ',
                'dissertation_topic' => 'ХХ АСР ЎЗБЕК НАСРИ НАМУНАЛАРИНИНГ УРДУ ТИЛИДАГИ ТАРЖИМАЛАРИДА МИЛЛИЙ КОЛОРИТНИНГ ИФОДАЛАНИШИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ШАМСИЕВА БАРНОХОН БАХРОМХОДЖАЕВНА',
                'dissertation_topic' => 'ТАРЖИМА МАТНИ МАДАНИЯТ ТРАНСФЕРИ СИФАТИДА (НАЦУМЭ СОСЭКИНИНГ «ҚАЛБ» АСАРИ АСОСИДА)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'АБДУЛЛАЕВА ДИЛАФРУЗ СУРАТИЛЛАЕВНА',
                'dissertation_topic' => 'ЗАМОНАВИЙ АРАБ ВА ЎЗБЕК ҲИКОЯЛАРИДА БАДИИЙ ПСИХОЛОГИЗМ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ШАМСИЕВА ШОҲИСТАХОН ҚУДРАТУЛЛАЕВНА',
                'dissertation_topic' => 'ХИТОЙ ВА ЎЗБЕК ТИЛЛАРИДАГИ МАИШИЙ ЭВФЕМИЗМЛАРНИНГ ЛИНГВОМАДАНИЙ ТАДҚИҚИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2020,
                'file_url' => '23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'YEON SANGHEUM',
                'dissertation_topic' => 'OʻZBEK TILIDA MODAL MA’NOLI KOʻMAKCHI FE’LLAR VA ULARNING KOREYS TILIDA IFODALANISHI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'БАХАДИРОВ ЖАХАНГИРМИРЗО АБДУМАЖИТОВИЧ',
                'dissertation_topic' => 'ЎЗБЕК ВА ИНГЛИЗ ТИЛЛАРИДАГИ ИЖТИМОИЙ РЕКЛАМАЛАРНИНГ ЛИНГВОМАДАНИЙ ТАДҚИҚИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2022,
                'file_url' => '25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'АСҚАРОВА ШАХНОЗА КАМОЛИДИНОВНА',
                'dissertation_topic' => 'ИНГЛИЗ ВА ЎЗБЕК ТИЛЛАРИДА ТАКРОРНИНГ ЛИНГВИСТИК ХУСУСИЯТЛАРИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2019,
                'file_url' => '26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'КЕНДЖАЕВА ГУЛРУХ ФАТТИЛЛОЕВНА',
                'dissertation_topic' => 'АБДУЛЛА ҚОДИРИЙНИНГ “ЎТКАН КУНЛАР” РОМАНИ ТАРЖИМАЛАРИДА МИЛЛИЙ МАНЗАРАНИНГ ЛИНГВОМАДАНИЙ ИФОДАСИ (АСЛИЯТ ВА М.САФАРОВ, К.ЭРМАКОВА, М.РИИЗ ТАРЖИМАЛАРИ АСОСИДА)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'SHUKUROV UKTAM BAXODIROVICH',
                'dissertation_topic' => 'BADIIY DISKURS KOGNITIV-PRAGMATIK MUNDARIJASINI SHAKLLANTIRUVCHI LISONIY VOSITALAR (o‘zbek va ingliz tillari materialida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'BOZOROV ORIF CHAMANOVICH',
                'dissertation_topic' => 'EPISTOLYAR ROMANDA VOQELIKNI BADIIY TASVIRLASH IMKONIYATLARI VA QAHRAMON MUAMMOSI (IOGANN VOLFGANG FON GYOTENING “YOSH VERTERNING IZTIROBLARI”',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'IZZATILLAYEV PARVIZ INOYATILLAYEVICH',
                'dissertation_topic' => 'ERON NAVOIYSHUNOSLIGI: TADQIQ, TALQIN VA TARJIMA',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'XOLMATOVA DILOROM ABDUSAMIYEVNA',
                'dissertation_topic' => 'ETNOGRAFIK TERMINOLOGIYA VA UNING LINGVISTIK TAHLILI (RUS VA O‘ZBEK TILLARI ASOSIDA)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'XOLIBEKOVA OMONGUL KENJABOYEVNA',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARIDA ZOONIM VA FITONIM KOMPONENTLI FRAZEOLOGIK BIRLIKLARNING SEMANTIK - STRUKTUR, LINGVOMADANIY TADQIQI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'SAFAROVA ZILOLA TOLIBOVNA',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TARBIYA ROMANLARINING SPETSIFIK BELGILARI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '33',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'YOROVА SАYYORА KАRIMOVNА',
                'dissertation_topic' => 'INGLIZ VА O‘ZBEK TIBBIY NUTQINING IJTIMOIY-MАDАNIY XUSUSIYATLАRI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '34',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'SAYFUTDINOVA MAFTUNA ABROR QIZI',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARI IQTISODIY DISKURSINING LINGVOPRAGMATIK XUSUSIYATLARI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '35',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'G‘AYBULLAYEVA XATIRA MURATJANOVNA',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARIDA BADIIY MATN TARJIMALARINING LINGVOMADANIY XUSUSIYATI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'AZZAMOV YUSUFJON RADJABOY O‘GʻLI',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARIDA GASTRONOMIYA TERMINOLOGIYASINING LINGVOKULTUROLOGIK VA TARJIMA XUSUSIYATLARI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '37',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'NARZULLAYEVA FIRUZA OLIMOVNA',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARIDA INSON BOSH QISMI A’ZOLARINI IFODALOVCHI LISONIY BIRLIKLAR SEMANTIKASI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'TURAYEVA UMIDA SHUXRATOVNA',
                'dissertation_topic' => 'INGLIZ VА OʻZBEK YURIDIK TERMINLАRINING CHOGʻISHTIRMА TАDQIQI (leksik, morfologik, tarjima va berilish xususiyatlari asosida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '39',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'YUSUPOV OYBEK NEMATJONOVICH',
                'dissertation_topic' => 'INGLIZ TILIDAN O‘ZBEK TILIGA BEVOSITA TARJIMA QILINGAN BADIIY MATNNING LINGVOKOGNITIV XUSUSIYATLARI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ШОДИЕВ ШАҲОБИДДИН ШАРОФИДДИНОВИЧ',
                'dissertation_topic' => 'ИНГЛИЗ УЙҒОНИШ ДАВРИ ВА ЖАДИДЛАР ТРАГИК АСАРЛАРИДАГИ СЕМАНТИК ИННОВАЦИЯЛАРНИНГ ЛИНГВО-ФАЛСАФИЙ АСПЕКТИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '41',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'КАХАROVA MOHIGUL YUSUFOVNA',
                'dissertation_topic' => 'INGLIZ VА O‘ZBEK BOLАLАR NАSRIDА O‘SMIRLАR RUHIYATI TАSVIRI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'HAKIMOVA SHOXISTA RAIMOVNA',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK LINGVOMAMLAKATSHUNOSLIK MATNLARI TARJIMASI MUAMMOLARI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'HALIMOVA MUHAYYOXON MUHAMMEDOVNA',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARIDA OLAMNING LISONIY MANZARASI VOQELASHUVIDA “HEAD/BOSH” SOMATIZMI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'ХАСАНОВА ФОТИМАХОН МАМАНОВНА',
                'dissertation_topic' => 'ИНГЛИЗ ВА ЎЗБЕК ТИЛЛАРИДА ҚАСАМЁД НУТҚИЙ ЖАНРИНИНГ ҚИЁСИЙ-ТИПОЛОГИК ТАДҚИҚИ',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2019,
                'file_url' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'SOBIROVA DILAFRUZ AKROM QIZI',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARIDA QO‘SHMA GAPLAR ORQALI IFODALANUVCHI  STILISTIK VOSITALARNING СHOG‘ISHTIRMA TADQIQI (takror, antiteza  va xiazm materiali asosida)',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'KAYUMOVA SHAXNOZA KOBILJONOVNA',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARIDA TAQINCHOQ NOMLARINING LINGVOKULTUROLOGIK TADQIQI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'NARMURODOVA GULNOZA ILHOM QIZI',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARIDA TA’ZIYA NUTQINING LINGVOMADANIY XUSUSIYATLARI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'MAMATALIYEVA NAVBAHOR XUJAMBERDIYEVNA',
                'dissertation_topic' => 'INGLIZ VA O‘ZBEK TILLARIDA “VATAN” MAZMUNLI AFORIZMLARNING SEMANTIKASI VA STRUKTURASI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'applicant_name' => 'JABBOROV ESHNAZAR',
                'dissertation_topic' => 'JAHON MA’RIFATCHILIK ADABIYOTI: G‘ARBIY YEVROPA VA O‘ZBEK ADABIYOTINING QIYOSIY TAHLILI',
                'locale_id' => 1,
                'academic_degree' => 'PhD',
                'specialty_code_and_name' => '10.00.06 – Qiyosiy-adabiyotshunoslik, chog`ishtirma tilshunoslik, tarjimashunoslik',
                'protection_year' => 2023,
                'file_url' => '50',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        // Insert data into the 'abstracts' table
        DB::table('abstracts')->insert($abstracts);
    }
}


//        $data = [
//            ['Axmedov Oybek Saporboyevich', '"Ingliz va o\'zbek tillarida soliq-bojxona terminlarining lingvistik tahlili va tarjima muammolari"', 'DSc', "10.00.06 – Qiyosiy-adabiyotshunoslik, chog'ishtirma tilshunoslik, tarjimashunoslik", '2011 yil', "https://tsuos.uz/wp-content/uploads/2018/08/ahmedov.pdf"],
//            ['Djumabayeva Jamila Sharipovna', "“O'zbek va ingliz tillarida leksik hamda stilistik graduonimiya”", 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2016 yil', "https://tsuos.uz/wp-content/uploads/2017/01/avtoref_jumabayeva.pdf"],
//            ['Djumanova Dilbar Rahimovna', '"Til aloqasi sharoitida so\'zning fonologik modeli"', 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2016 yil', "https://tsuos.uz/wp-content/uploads/2017/01/avtoref_jumanova.pdf"],
//            ['Kamilova Saodat Ergashevna', '“XX asr oxiri – 21-asr boshlari rus va oʻzbek adabiyotida qissa janri poetikasining rivojlanishi”', 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2016 yil', "https://tsuos.uz/wp-content/uploads/2017/01/avtoref_kamilovas.pdf"],
//            ['Nasirov Abdurahim Abdimutalipovich', "“Fransuz, o'zbek va rus tillaridagi proverbial frazeologizmlarning semantik-stilistik va milliy-madaniy xususiyatlari”", 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2016 yil', "https://tsuos.uz/wp-content/uploads/2017/01/avtoref_nosirov.pdf"],
//            ['Paluanova Halifa Dariboevna', "“Ingliz, o'zbek, rus va qoraqalpoq tillarida ekologik terminlaring derivasiong'semantik prinsiplari”", 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2016 yil', "https://tsuos.uz/wp-content/uploads/2017/01/avtoref_paluanova.pdf"],
//            ['Xalliyeva Gulnoz Iskandarovna', "“XX asr rus sharqshunosligida o'zbek mumtoz adabiyoti tadqiqi”", 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2016 yil', "https://tsuos.uz/wp-content/uploads/2017/01/avtoref_hallieva.pdf"],
//            ['Baxronova Dilrabo Keldiyorovna', "“Antropozoomorfizmlarning semantik va lingvokulturologik xususiyatlari (o'zbek va ispan tillari materialida)", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2018/08/baxronova.pdf"],
//            ["Jo'rayeva Malohat Muhamadovna", "“Fransuz va o'zbek ertaklarida modallik kategoriyasining lingvokognitiv, milliy-madaniy xususiyatlari”", 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2018/02/jurayevam.pdf"],
//            ['Qodirbekova Durdona Xikmatullaevna', "“Inglizcha-o'zbekcha axborot-kommunikatsiya texnologiyalari terminologiyasi va uning leksikografik xususiyatlari”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2017/08/%D0%9A%D0%B0%D0%B4%D0%B8%D1%80%D0%B1%D0%B5%D0%BA%D0%BE%D0%B2%D0%B0-PhD-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D1%84%D0%B5%D1%80%D0%B0%D1%82.pdf"],
//            ['Kdirbayeva Gulzira Qurbonboevna', '“Man” – “adam” konseptosferasi birliklarining lingvomadaniy va lingvokognitiv xususiyatlari (ingliz va qoraqalpoq tillari misolida)”', 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2018/02/kdirbayeva.pdf"],
//            ['Samigova Xushnuda Botirovna', "“Ingliz va o'zbek nutq madaniyatining ritoric aspektining qiyosiy tadqiqi”", 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2017/10/samigova_h.pdf"],
//            ['Sharipova Aziza Abdumanapovna', "“Stilistik sinonimlar tarjimasining lingvokul-turologik xususiyatlari (ingliz va o'zbek tillari materiallari asosida)”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2018/02/sharipova_a.pdf"],
//            ['Shirinova Raima Xakimovna', '“Olam milliy manzarasining badiiy tarjimada qayta yaratilishi”', 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2017/09/shirinova_r.pdf"],
//            ['Teshaboyeva Ziyodaxon Qodirovna', '“Boburnoma”ning inglizcha tarjimalaridagi frazeologik birliklar va tahrir milliy-madaniy xususiyatlari”', 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2018/02/teshaboyeva.pdf"],
//            ['Tuxtaxodjayeva Nargiza Akmalovna', "“Badiiy tarjimada lingvo-kulturemalarning ifodalanishi (ingliz va o'zbek tillari misolida)”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2017/10/tuhtahodjayeva_n.pdf"],
//            ['Xolmurodova Leyla Eshquvatovna', '“Ingliz va fransuz tillaridagi obrazli va motivlashgan frazeologizmlarning tematik-ideografik talqini (lingvomadaniy aspekt)”', 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2018/02/holmuradova.pdf"],
//            ["Xudjayeva Ra'no Mutalibjonovna", "“Ingliz va o'zbek tillaridagi genetik bog'lanmagan leksik omonimlarning miqdori va leksikografik talqini”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2017/10/hudjayeva_r.pdf"],
//            ["Yo'ldoshev Ulug'bek Ravshanbekovich", "“Xajviy matnlar tarjimasining lingvostilistik va lingvokulturorlogik xususiyatlari” (ingliz tiliga tarjima qilingan o'zbek xalq latifalari misolida)", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2018/02/yuldoshev.pdf"],
//            ['Yuldashev Akmal Gulamjanovich', "“Idiomatik qo'shma so'zlarning lingvokognitiv aspekti” (ingliz va o'zbek tillari misolida)", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2017 yil', "https://tsuos.uz/wp-content/uploads/2018/02/yuldashev_a.pdf"],
//            ['Djafarova Dildora Ilxomovna', "“Fransuz va o'zbek tillarida leksik motivlashuvning milliy-madaniy xususiyatlari”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ["Qosimova Ra'no Raxmatulloyevna", "“O'zbek to'y va motam marosim folklor matnlarining inglizcha tarjimasida etnografizmlarning namunalari”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ["Mo'minova Aziza Arslanovna", "“Fransuz, o'zbek va rus tillarida undashni ifodalovchi til birliklarining lingvomadaniy xususiyatlari”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ['Qosimova Nafisa Farhodovna', "“Lisoniy belgi asimmetriyasi va uning so'roq gap tarjimasida voqelanishi”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ['Sapayeva Feruza Davlatovna', "“Maxtumquli she'rlari o'zbekcha tarjima qiyosiy tahlili”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ['Sayfullaev Anvar Islomovich', '“Preposition va kwmakchilarining nominative-sintagmativ mavkei va tipologik strukturaviy makomi”', 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ['Toirova Nargiza Isakovna', '“Badiiy adabiyotda koʻzgu va surat ramzlarining gʻoyaviy-estetik asarlari (Omon Muxtor va Oskar Uayld asarlari asosida)”', 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ['Xajiyeva Feruza Melsovna', '“Biografik roman janri xususiyatlari (I.Stoun, M.Qoriev va N.Normatov asarlari qiyosida)”', 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ["Xodjayeva Dilafro'z Izatilloyevna", "“Tilshunoslik terminlarining leksikografik tahlili (ingliz, rus va o'zbek tillari izohli lug'atlari materiallari misolida)”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ['Xoliqov Bahodir Aliqulovich', '“Detektiv romanlarda voqelikning badiiy talqinini tizimli modellashtirish (Mario Pyuzoning “The Godfather” va Tohir Malikning “Shaytanat”)', 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ['Xoshimova Dildora Madaminovna', '“Boburnoma” matnidagi tasviriy tadqiqotning ingliz tiliga tarjimalari tadqiqi”', 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ["Xoshimxo'jayeva Mohirux Muzaffarovna", "“Olamning lisoniy tasvirida fitonimlar (ingliz, rus va o'zbek tillari misolida”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2018'],
//            ['Asqarova Shaxnoza Kamolidinovna', "Ingliz va o'zbek tillarida takrorning lingvistik xususiyatlari", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma", 'tilshunoslik va tarjimashunoslik', "2019"],
//            ['Xodjayeva Nilufar Bekmuratovna', "Premchand asarlari o'zbekcha tarjimalarining leksik-stilistik xususiyatlari", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2019', "https://tsuos.uz/wp-content/uploads/2018/02/%D0%90%D1%81%D2%9B%D0%B0%D1%80%D0%BE%D0%B2%D0%B0-%D0%A8%D0%B0%D1%85%D0%BD%D0%BE%D0%B7%D0%B0-%D0%9A%D0%B0%D0%BC%D0%BE%D0%BB%D0%B8%D0%B4%D0%B8%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0.pdf"],
//            ['Raxmatjonova Kamola Abdumutal kizi', "Hindiy va o'zbek tillarida son va kelishik grammatik katyegoriyalarining chog'ishtirma-tipologik tadqiqi", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2020', "https://tsuos.uz/wp-content/uploads/2018/02/%D0%A5%D0%BE%D0%B4%D0%B6%D0%B0%D0%B5%D0%B2%D0%B0-%D0%9D%D0%B8%D0%BB%D1%83%D1%84%D0%B0%D1%80-%D0%91%D0%B5%D0%BA%D0%BC%D1%83%D1%80%D0%B0%D1%82%D0%BE%D0%B2%D0%BD%D0%B0.pdf"],
//            ['Shamsiyeva Shohista Qudratullayevna', "Xitoy va o'zbek tillaridagi maishiy evfemizmlarning lingvomadaniy tadqiqi", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2020', "https://tsuos.uz/wp-content/uploads/2018/02/%D0%A0%D0%B0%D1%85%D0%BC%D0%B0%D1%82%D0%B6%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0-%D0%9A%D0%B0%D0%BC%D0%BE%D0%BB%D0%B0-%D0%90%D0%B1%D0%B4%D1%83%D0%BC%D1%83%D1%82%D0%B0%D0%BB-%D0%BA%D0%B8%D0%B7%D0%B8.pdf"],
//            ['Turapova Nargiza Axmedovna', "Yapon va o'zbek tillari somatik frazeologizmlarining chog'ishtirma tahlili (lingvomadaniy aspyekt)", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2020', "https://tsuos.uz/wp-content/uploads/2018/02/%D0%A8%D0%B0%D0%BC%D1%81%D0%B8%D0%B5%D0%B2%D0%B0-%D0%A8%D0%BE%D2%B3%D0%B8%D1%81%D1%82%D0%B0-%D2%9A%D1%83%D0%B4%D1%80%D0%B0%D1%82%D1%83%D0%BB%D0%BB%D0%B0%D0%B5%D0%B2%D0%BD%D0%B0.pdf"],
//            ['Zikrullayeva Xusniya Baxtiyorovna', "Ingliz, turk va o'zbyek ilmiy-tyexnikaviy tarjimada lyeksik-syemantik transformasiyalar", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2020', "https://tsuos.uz/wp-content/uploads/2018/02/%D0%A2%D1%83%D1%80%D0%B0%D0%BF%D0%BE%D0%B2%D0%B0-%D0%9D%D0%B0%D1%80%D0%B3%D0%B8%D0%B7%D0%B0-%D0%90%D1%85%D0%BC%D0%B5%D0%B4%D0%BE%D0%B2%D0%BD%D0%B0.pdf"],
//            ['Ismatullayeva Nargiza Rasuljanovna', "Xitoy va o'zbek tillarida lakunalarning voqelanishi", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2021 yil', "https://tsuos.uz/wp-content/uploads/2018/02/%D0%97%D0%B8%D0%BA%D1%80%D1%83%D0%BB%D0%BB%D0%B0%D0%B5%D0%B2%D0%B0-%D0%A5%D1%83%D1%81%D0%BD%D0%B8%D1%8F-%D0%91%D0%B0%D1%85%D1%82%D0%B8%D1%91%D1%80%D0%BE%D0%B2%D0%BD%D0%B0.pdf"],
//            ['Saidakbarova Saodat Parxadjanovna', "Ingliz va o'zbek tillarida gastronomik frazyeologizmlarning lingvomadaniy xususiyatlari", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2021 yil', "https://tsuos.uz/wp-content/uploads/2018/02/%D0%98%D1%81%D0%BC%D0%B0%D1%82%D1%83%D0%BB%D0%BB%D0%B0%D0%B5%D0%B2%D0%B0-%D0%9D%D0%B0%D1%80%D0%B3%D0%B8%D0%B7%D0%B0-%D0%A0%D0%B0%D1%81%D1%83%D0%BB%D0%B6%D0%B0%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0.pdf"],
//            ['Sharaxmetova Muxlisa Ansaritdinovna', '“Bobur urducha tarjimasida muallif uslubiga xos leksik-semantik ishlab chiqarishning ask etishi”', 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2021 yil',  "https://tsuos.uz/wp-content/uploads/2018/02/%D0%A1%D0%B0%D0%B8%D0%B4%D0%B0%D0%BA%D0%B1%D0%B0%D1%80%D0%BE%D0%B2%D0%B0-%D0%A1%D0%B0%D0%BE%D0%B4%D0%B0%D1%82-%D0%9F%D0%B0%D1%80%D1%85%D0%B0%D0%B4%D0%B6%D0%B0%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0.pdf"],
//            ['Xomidov Xayrullo Xudoyorovich', "O'zbek qissa valarining roman turkcha tarjimalarida milliylik, badiiylik va lisoniy adekvatik masalalari", 'DSc', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2021 yil', "https://tsuos.uz/wp-content/uploads/2018/02/%D0%A5%D0%BE%D0%BC%D0%B8%D0%B4%D0%BE%D0%B2-%D0%A5%D0%B0%D0%B9%D1%80%D1%83%D0%BB%D0%BB%D0%BE-%D0%A5%D1%83%D0%B4%D0%BE%D1%91%D1%80%D0%BE%D0%B2%D0%B8%D1%87.pdf"],
//            ['Abdullayeva Dilafruz Suratillayevna', "Zamonaviy arab va o'zbek hiqoyalarida badiiy psixologizm (G'ada As-samman va Zulfiya Qurolboy qizi hikoyalari misolida)", 'PhD', "10.00.06-Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2022', "https://tsuos.uz/wp-content/uploads/2022/12/AVTOREFARAT.pdf"],
//            ['Ashirbayeva Diloram Ravshanovna', "“Koreys va o'zbek diskursida murojaat birlik qiyosiy tadqiqi”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik ixtisosligi.", '2022', "https://tsuos.uz/wp-content/uploads/2018/02/5.-%D0%91%D0%B0%D1%85%D0%B0%D0%B4%D0%B8%D1%80%D0%BE%D0%B2-%D0%96%D0%B0%D1%85%D0%B0%D0%BD%D0%B3%D0%B8%D1%80%D0%BC%D0%B8%D1%80%D0%B7%D0%BE-%D0%90%D0%B1%D0%B4%D1%83%D0%BC%D0%B0%D0%B6%D0%B8%D1%82%D0%BE%D0%B2%D0%B8%D1%87.pdf"],
//            ['Baxadirov Jaxangirmirzo Abdumajitovich', "O'zbek va ingliz tillaridagi ijtimoiy reklamalarning lingvomadaniy tadqiqi", 'PhD', "10.00.06-Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2022', "https://tsuos.uz/wp-content/uploads/2022/05/O%CA%BBzbek-va-ispan-tillarida-olam-manzarasining-lingvokognitiv-kategoriyalanishi.pdf"],
//            ['Dilrabo Keldiyorovna Baxronova', 'Oʻzbek va ispan tillarida olam manzarasining lingvokognitiv kategoriyalanishi', 'DSc', "10.00.06-Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2022', "https://tsuos.uz/wp-content/uploads/2018/02/FORS-VA-OZBEK-TILLARIDA-TERMIN-YASASH-PRINSPLARI-VA-MUAMMOLARI.pdf"],
//            ['Mirzaxmedova Xulkar Vasilovna', "Fors Va O'zbek Tillarida Termin Yasash Prinsplari Va muammolari", 'DSc', '10.00.06 –Qiyosiy adabiyotshunoslik, chogʻishtirma tilshunoslik va tarjimashunoslik', '2022', "https://tsuos.uz/wp-content/uploads/2022/12/AVTOREFARAT-1.pdf"],
//            ['Sadriddinzoda Safiya Shaxobiddinovna', "“Demonologik leksikaning semantik xususiyatlari va pragma-madaniy vositalarii (ingliz, o'zbek va rus adabiyoti asosida)”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik ixtisosligi.", '2022', "https://tsuos.uz/wp-content/uploads/2018/02/15.-%D0%A8%D0%B0%D0%BC%D1%81%D0%B8%D0%B5%D0%B2%D0%B0-%D0%91%D0%B0%D1%80%D0%BD%D0%BE%D1%85%D0%BE%D0%BD-%D0%91%D0%B0%D1%85%D1%80%D0%BE%D0%BC%D1%85%D0%BE%D0%B4%D0%B6%D0%B0%D0%B5%D0%B2%D0%BD%D0%B0.pdf"],
//            ['Shamsiyev Barnoxon Baxromxodjayevna', 'Tarjima matni madaniyat transferi sifatida (Nasume Sosekining “Qalb” asari asosida)', 'PhD', "10.00.06-Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2022', "https://tsuos.uz/wp-content/uploads/2018/02/15.-%D0%A8%D0%B0%D0%BC%D1%81%D0%B8%D0%B5%D0%B2%D0%B0-%D0%91%D0%B0%D1%80%D0%BD%D0%BE%D1%85%D0%BE%D0%BD-%D0%91%D0%B0%D1%85%D1%80%D0%BE%D0%BC%D1%85%D0%BE%D0%B4%D0%B6%D0%B0%D0%B5%D0%B2%D0%BD%D0%B0.pdf"],
//            ['Umarova Mohira Azim qizi', "“XX asr o'zbek nasri namunalarining urdu tilidagi tarjimalarida milliy koloritning ifodalanishi”", 'PhD', "10.00.06 – Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik ixtisosligi bo'yicha.", '2022', "https://tsuos.uz/wp-content/uploads/2022/11/Avtoreferat-1.pdf"],
//            ['Yeon Sangheumning', 'Oʻzbek tilida modal maʼnoli koʻmakchi feʼllar va fayl koreys tilida ifodalanishi', 'PhD', "10.00.06-Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2022', "https://tsuos.uz/wp-content/uploads/2018/02/O%CA%BBzbek-tilida-modal-ma%E2%80%99noli-ko%CA%BBmakchi-fe%E2%80%99llar-va-ularning-koreys-tilida-ifodalanishi.pdf"],
//            ['Jo Min Yong', "O'zbek va koreys tillarida o'xshatishlarning lingvomadaniy tadqiqi", 'PhD', "10.00.06-Qiyosiy adabiyotshunoslik, chog'ishtirma tilshunoslik va tarjimashunoslik", '2023 yil', "https://drive.google.com/file/d/1rAzlmYKYpYw-pLox9EYH_KgjmJCDB7z8/view",],
//        ];
//        foreach ($data as $abstract) {
//            DB::table('abstracts')->insert([
//                'applicant_name' => $abstract[0],
//                'dissertation_topic' => $abstract[1],
//                'academic_degree' => $abstract[2],
//                'specialty_code_and_name' => $abstract[3],
//                'protection_year' => $abstract[4],
//            ]);
//        }
