<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConventionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $abstracts = [
            [
                'name' => 'Jurnal haqida',
                'description' => 'Jurnal haqida',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Jurnal haqida. O jurnale. About the journal.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jurnal nizomi',
                'description' => 'Jurnal nizomi 19.03.2024',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Jurnal nizomi (2).pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maqola talablari',
                'description' => 'Maqola talablari 2024',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Komporavistika jurnali axborot xati 07.2024.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tahririyat kengashi',
                'description' => 'TAHRIRIYAT KENGASHI',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/TAHRIRIYAT KENGASHI.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tahririyat hay’ati',
                'description' => 'TAHRIRIYAT HAY’ATI',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/TAHRIRIYAT HAY’ATI.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Komparativistika jurnaliga namunaviy maqola',
                'description' => 'Komparativistika jurnaliga namunaviy maqola',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Comparative Studiesga maqola Namuna.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Komparativistaika jurnali guvohnomasi',
                'description' => 'Komparativistaika jurnali guvohnomasi',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/309609-39b0667a137152b4195d4bef4d2db44f.pdf',
                'photo_url' => 'convention_files/photos/img_3.png',
                'type' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Axmedova Aziza Komilovna',
                'description' => 'Axmedova Aziza Komilovna',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Axmedova Aziza Komilovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Begmatova Sohiba Mustafoyevna',
                'description' => 'Begmatova Sohiba Mustafoyevna',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Begmatova Sohiba Mustafoyevna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jo‘raqulov Uzоq Haydarovich',
                'description' => 'Jo‘raqulov Uzоq Haydarovich',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Jo‘raqulov Uzоq Haydarovich.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mannonova Feruzabonu Sherali qizi',
                'description' => 'Mannonova Feruzabonu Sherali qizi',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Mannonova Feruzabonu Sherali qizi.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Murodov G‘ayrat Nekovich',
                'description' => 'Murodov G‘ayrat Nekovich',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Murodov G‘ayrat Nekovich.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sabirova Zebo Zokirovna',
                'description' => 'Sabirova Zebo Zokirovna',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Sabirova Zebo Zokirovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'To‘raeva Bahor Bahriddinovna',
                'description' => 'To‘raeva Bahor Bahriddinovna',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/To‘raeva Bahor Bahriddinovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Umarova Komila Samatovna',
                'description' => 'Umarova Komila Samatovna',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Umarova Komila Samatovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Xalliyeva Gulnoz Iskandarovna',
                'description' => 'Xalliyeva Gulnoz Iskandarovna',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Xalliyeva Gulnoz Iskandarovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yuldoshova Shaxnoza Azimbayevna',
                'description' => 'Yuldoshova Shaxnoza Azimbayevna',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Yuldoshova Shaxnoza Azimbayevna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '1-son jurnal',
                'description' => '1-сон журнал',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/54465445.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hamdаmov Ulug‘bek',
                'description' => 'Hamdаmov Ulug‘bek',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Hamdаmov Ulug‘bek.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ko‘chimov Ulug‘bek',
                'description' => 'Ko‘chimov Ulug‘bek',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Ko‘chimov Ulug‘bek.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mirzaakhmedova Makhliyo',
                'description' => 'Mirzaakhmedova Makhliyo',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Mirzaakhmedova Makhliyo.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rahimova Bekposhsha',
                'description' => 'Rahimova Bekposhsha',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Rahimova Bekposhsha.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Raximova Umida',
                'description' => 'Raximova Umida',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Raximova Umida.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ruzmatova Dilnoza',
                'description' => 'Ruzmatova Dilnoza',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Ruzmatova Dilnoza.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teshayeva Gulnoza',
                'description' => 'Teshayeva Gulnoza',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Teshayeva Gulnoza.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ahmedova Shoira',
                'description' => 'Ahmedova Shoira',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Ахмедова Шоира.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kasymov Abdugapir',
                'description' => 'Kasymov Abdugapir',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Касымов Абдугапир.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Xalliyeva Gulnoz',
                'description' => 'Xalliyeva Gulnoz',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Халлиева Гулноз.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '2-son jurnal',
                'description' => '2-son jurnal',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Komparativistika jurnali №2.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert data into the 'conventions' table
        DB::table('conventions')->insert($abstracts);
    }
}
