<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConventionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert parent conventions first
        $parentConventions = [
            [
                'name' => 'JURNAL HAQIDA',
                'description' => 'JURNAL HAQIDA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Jurnal haqida. O jurnale. About the journal.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JURNAL NIZOMI',
                'description' => 'JURNAL NIZOMI 19.03.2024',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Jurnal nizomi (2).pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MAQOLA TALABLARI',
                'description' => 'MAQOLA TALABLARI 2024',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Komporavistika jurnali axborot xati 07.2024.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TAHRIRIYAT KENGASHI',
                'description' => 'TAHRIRIYAT KENGASHI',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/TAHRIRIYAT KENGASHI.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TAHRIRIYAT HAY’ATI',
                'description' => 'TAHRIRIYAT HAY’ATI',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/TAHRIRIYAT HAY’ATI.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KOMPARATIVISTIKA JURNALIGA NAMUNAVIY MAQOLA',
                'description' => 'KOMPARATIVISTIKA JURNALIGA NAMUNAVIY MAQOLA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Comparative Studiesga maqola Namuna.pdf',
                'photo_url' => 'convention_files/photos/img_2.png',
                'type' => '0',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KOMPARATIVISTAİKA JURNALI GUVOHNOMASI',
                'description' => 'KOMPARATIVISTAİKA JURNALI GUVOHNOMASI',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/309609-39b0667a137152b4195d4bef4d2db44f.pdf',
                'photo_url' => 'convention_files/photos/img_3.png',
                'type' => '0',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '1-SON JURNAL',
                'description' => '1-SON JURNAL',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/54465445.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '2-SON JURNAL',
                'description' => '2-SON JURNAL',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Komparativistika jurnali №2.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert parent conventions
        DB::table('conventions')->insert($parentConventions);

        // Retrieve the IDs of the inserted parent conventions
        $parentIds = DB::table('conventions')->whereIn('name', [
            '1-SON JURNAL',
            '2-SON JURNAL'
        ])->pluck('id', 'name');

        // Insert child conventions
        $childConventions = [
            [
                'name' => 'AXMEDOVA AZIZA KOMILOVNA',
                'description' => 'AXMEDOVA AZIZA KOMILOVNA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Axmedova Aziza Komilovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BEGMATOVA SOHIBA MUSTAFOYEVNA',
                'description' => 'BEGMATOVA SOHIBA MUSTAFOYEVNA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Begmatova Sohiba Mustafoyevna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JO‘RAQULOV UZОQ HAYDAROVICH',
                'description' => 'JO‘RAQULOV UZОQ HAYDAROVICH',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Jo‘raqulov Uzоq Haydarovich.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MANNONOVA FERUZABONU SHERALI QIZI',
                'description' => 'MANNONOVA FERUZABONU SHERALI QIZI',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Mannonova Feruzabonu Sherali qizi.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MURODOV G‘AYRAT NEKOVICH',
                'description' => 'MURODOV G‘AYRAT NEKOVICH',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Murodov G‘ayrat Nekovich.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SABIROVA ZEBO ZOKIROVNA',
                'description' => 'SABIROVA ZEBO ZOKIROVNA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Sabirova Zebo Zokirovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TO‘RAEVA BAHOR BAHRIDDINOVNA',
                'description' => 'TO‘RAEVA BAHOR BAHRIDDINOVNA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/To‘raeva Bahor Bahriddinovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'UMAROVA KOMILA SAMATOVNA',
                'description' => 'UMAROVA KOMILA SAMATOVNA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Umarova Komila Samatovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'XALLIYEVA GULNOZ ISKANDAROVNA',
                'description' => 'XALLIYEVA GULNOZ ISKANDAROVNA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Xalliyeva Gulnoz Iskandarovna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YULDOSHOVA SHAXNOZA AZIMBAYEVNA',
                'description' => 'YULDOSHOVA SHAXNOZA AZIMBAYEVNA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Yuldoshova Shaxnoza Azimbayevna.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['1-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HAMDАMOV ULUG‘BEK',
                'description' => 'HAMDАMOV ULUG‘BEK',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Hamdаmov Ulug‘bek.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KO‘CHIMOV ULUG‘BEK',
                'description' => 'KO‘CHIMOV ULUG‘BEK',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Ko‘chimov Ulug‘bek.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MIRZAAKHMEDOVA MAKHLIYO',
                'description' => 'MIRZAAKHMEDOVA MAKHLIYO',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Mirzaakhmedova Makhliyo.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAHIMOVA BEKPOSHCHA',
                'description' => 'RAHIMOVA BEKPOSHCHA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Rahimova Bekposhsha.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAXIMOVA UMIDA',
                'description' => 'RAXIMOVA UMIDA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Raximova Umida.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RUZMATOVA DILNOZA',
                'description' => 'RUZMATOVA DILNOZA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Ruzmatova Dilnoza.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TESHAYEVA GULNOZA',
                'description' => 'TESHAYEVA GULNOZA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Teshayeva Gulnoza.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AHMEDOVA SHOIRA',
                'description' => 'AHMEDOVA SHOIRA',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Ахмедова Шоира.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KASYMOV ABDUGAPIR',
                'description' => 'KASYMOV ABDUGAPIR',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Касымов Абдугапир.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'XALLIYEVA GULNOZ',
                'description' => 'XALLIYEVA GULNOZ',
                'locale_id' => 1,
                'file_url' => 'convention_files/files/Халлиева Гулноз.pdf',
                'photo_url' => 'convention_files/photos/img_4.png',
                'type' => '1',
                'parent_id' => $parentIds['2-SON JURNAL'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert child conventions
        DB::table('conventions')->insert($childConventions);
    }
}
