<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DissertationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $abstracts = [
            [
                'country' => 'Uzbekistan',
                'author' => 'Б.Х. Муртазоев-1992',
                'locale_id' => 1,
                'topic' => 'Алишер Навоий "Сабъаи сайёр" ва Хусрав Деҳлавий "Ҳашт беҳишт" достонларининг қиёсий таҳлили',
                'thesis_date' => '1992-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/32302',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Қудратуллаев Ҳ. С. -1998 ',
                'locale_id' => 1,
                'topic' => '"Бобурнома" нинг тарихий-адабий ва услубий таҳлили (Навоий,Бобур,Хондамир ва Восифий насрининг қиёсий таҳлили асосида',
                'thesis_date' => '1998-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28459',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Шомусаров Ш. Ғ. -1998',
                'locale_id' => 1,
                'topic' => 'Араб ва ўзбек фольклори тарихий-қиёсий таҳлили',
                'thesis_date' => '1998-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28498',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Исомиддинов Ф. -2001',
                'locale_id' => 1,
                'topic' => 'Шайх Санъон ҳақидаги қиссаларнинг қиёсий таҳлили',
                'thesis_date' => '2001-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28653',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Собиров М. -2002',
                'locale_id' => 1,
                'topic' => '"Бобурнома"нинг инглизча таржималарида муаллиф услуби ва бадииятини қайта тиклаш муаммолари (Лейден-Эрскин, Бевериж ва Текстон таржималарининг қиёсий таҳлили асосида)',
                'thesis_date' => '2002-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/35796',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Каримов Р. -2003',
                'locale_id' => 1,
                'topic' => '"Бобурнома"даги шеърлар хорижий таржималарининг қиёсий таҳлили',
                'thesis_date' => '2003-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28873',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Маматқулова Х.А. -2010',
                'locale_id' => 1,
                'topic' => 'Навоийнинг "Лайли ва Мажнун" Шекспирнинг "Ромео ва Жульетта" асарларининг қиёсий тадқиқи',
                'thesis_date' => '2010-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/34862',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Жўраева Ф. Ё. -2000',
                'locale_id' => 1,
                'topic' => 'Типологик образларнинг қиёсий таҳлили(Лев Толстойнинг"Ҳожимурод" ва Худойберди Тўхтабоевнинг"Қасоскорнинг олтин боши"асарлари мисолида)',
                'thesis_date' => '2000-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28562',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Халлиева Гулноз Искандаровна -2016',
                'locale_id' => 1,
                'topic' => 'ХХ аср шарқшунослигида ўзбек мумтоз адабиёти тадқиқи',
                'thesis_date' => '2016-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/39254',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Халлиева Гулноз Искандаровна -2016',
//                'locale_id' => 1,
//                'topic' => 'ХХ аср шарқшунослигида ўзбек мумтоз адабиёти тадқиқи',
//                'thesis_date' => '2016-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/39254',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Йўлдошев У. Р. -2017',
                'locale_id' => 1,
                'topic' => 'Ҳажвий матнлар таржимасининг лингвостилистик ва лингвокультурологик хусусиятлари (инглиз тилига таржима қилинган ўзбек халқ латифалари мисолида)',
                'thesis_date' => '2017-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43032',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Жўраева М. М. -2017',
                'locale_id' => 1,
                'topic' => 'Француз ва ўзбек эртакларида модаллик категориясининг лингвокогнитив, миллий-маданий хусусиятлари',
                'thesis_date' => '2017-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42307',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Бабаджанова У. Б. -2018',
                'locale_id' => 1,
                'topic' => '"Саёд ва Ҳамро" достонининг туркий версия ва вариантлари (Ўрта Осиё, турк ва Озарбайжон версиялари)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42768',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Ҳайитов Шуҳрат Мойлиевич -2018',
                'locale_id' => 1,
                'topic' => 'Бобур ижодининг хорижда ўрганилиши (ўзбекча-туркча манбалар қиёсий таҳлили)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/44294',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Сапаева Ф.Д. -2018',
                'locale_id' => 1,
                'topic' => 'Махтумқули шеърлари ўзбекча таржималарининг қиёсий таҳлили',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42881',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Касимова Р. Р. -2018',
                'locale_id' => 1,
                'topic' => 'Ўзбек тўй ва мотам маросим фольклори матнларининг инглизча таржимасида этнографизмларнинг берилиши',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43227',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Жумаев Р .Н. -2018',
                'locale_id' => 1,
                'topic' => '"Маснавий маънавий" ва "Лисон ут-тайр"даги ҳикоятларнинг қиёсий таҳлили',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42707',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Тоирова Н. И. -2018',
                'locale_id' => 1,
                'topic' => 'Бадиий адабиётда кўзгу ва сурат рамзларининг ғоявий-эстетик вазифалари (Омон Мухтор ва Оскар Уайльд асарлари мисолида)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43271',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Хошимова Д. М. -2018',
                'locale_id' => 1,
                'topic' => '"Бобурнома" матнидаги тасвирий воситаларнинг инглиз тилига таржималари тадқиқи',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43062',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Холиков Б. А. -2018',
                'locale_id' => 1,
                'topic' => 'Детектив романларда воқеликнинг бадиий талқинини тизимли моделлаштириш (Марио Пьюзонинг "Чўқинтирган ота" ("The godfather") ва Тоҳир Маликнинг "Шайтанат" асарлари мисолида)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42941',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Хажиева Ф. М. -2018',
                'locale_id' => 1,
                'topic' => 'Биографик роман жанри хусусиятлари (И. Стоун, М.Қориев ва Н. Норматов асарлари қиёсида)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Хошимова Д. М. -2018',
                'locale_id' => 1,
                'topic' => '"Бобурнома" матнидаги тасвирий воситаларнинг инглиз тилига таржималари тадқиқи',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43062',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Абдувахабова Махина Азатовна -2019',
                'locale_id' => 1,
                'topic' => 'Инглиз, итальян ва ўзбек фольклор матнларида гендернинг тил воситаларида ифодаланиши',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48755',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Сариев Санъатжон Матчонбоевич -2019',
                'locale_id' => 1,
                'topic' => '"Гўрўғли" туркуми достонларининг оғзаки ва қўлёзма нусхаларини қиёсий ўрганиш',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48666',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Қурбонов Парда Ахмедович -2019',
                'locale_id' => 1,
                'topic' => '"Байрон ижодида шарқ ва шарқона мотивлар тавсифи (қиёс ва таржима)"',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48660',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Абдуллаева Наргиза Эркиновна -2019',
                'locale_id' => 1,
                'topic' => 'Инглиз ва ўзбек халқ мақолларидаги градуонимик муносабатларнинг лингвопрагматик хусусиятлари',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48534',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Алламбергенова Нодира Гулмурзаевна -2019',
                'locale_id' => 1,
                'topic' => '"Алпомиш" достонининг ўзбек ва қорақалпоқ версиялари қиёсий типологияси',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48517',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Султанов Тулкин Иргашевич -2019',
                'locale_id' => 1,
                'topic' => 'Алишер Навоий ва Озарбайжон адабиёти: тарихий илдизлар, анъаналар, ворисийлик(Кишварий ва содиқий асарлари мисолида)',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48352',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Рахматова Меҳринисо Мусиновна -2019',
                'locale_id' => 1,
                'topic' => 'Инглиз,Ўзбек ва тожик миллий маданиятида "гўзаллик" концептининг лисоний хусусиятлари',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48341',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Мардиев Тўлқин Кулибаевич -2019',
                'locale_id' => 1,
                'topic' => 'Инглиз ва ўзбек тилларида инсон туйғулари ифодаланишининг концептуал таҳлили',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48316',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Юсупова Дилновоз Раҳмоновна -2019',
                'locale_id' => 1,
                'topic' => 'Темурийлар давридаги арузга доир рисолаларнинг қиёсий таҳлили',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48188',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Хамидов Хусрав Садуллоевич -2019',
                'locale_id' => 1,
                'topic' => 'Жалолиддин Румийнинг «Маснавийи маънавий» асаридаги ҳикоятларнинг генезиси, мазмуни ва композицион қурилишининг қиёсий таҳлили',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47980',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Умурзоқов Баҳриддин Сафарович -2019',
                'locale_id' => 1,
                'topic' => 'Алий Сафийнинг илмий-адабий мероси ва унинг «Рашаҳот айну-л-ҳаёт» асарининг қиёсий-текстологик тадқиқи',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47873',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Файзуллоев Отабек Мухамадович -2019',
                'locale_id' => 1,
                'topic' => 'Ўзбек фольклоридаги лингвокультуремаларнинг инглизча таржимада берилиши (болалар фольклори ва эртаклар мисолида)',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47838',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Рустамов Илхом Турсунович -2019',
                'locale_id' => 1,
                'topic' => 'Кичик жанр матнларнинг прагматик когнитив ва миллий маданий моҳияти (Ўзбек ва инглиз латифалари мисолида)',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47736',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Насирдинова Ёркиной Абдумухторовна -2019',
                'locale_id' => 1,
                'topic' => 'Ўзбек фольклори ва мумтоз адабиёти намуналари француз тилида (Реми Дор таржималари асoсида)',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47612',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Ходжаева Нилуфар Бекмуратовна -2019',
                'locale_id' => 1,
                'topic' => 'Премчанд асарлари ўзбекча таржималарининг лексик-стилистик хусусиятлари',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47591',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Исмоилов Ильёс Абдукаюмович -2019',
                'locale_id' => 1,
                'topic' => 'Алишер Навоий "Садди Искандарий" достонининг қиёсий таҳлили',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/44057',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Дадабоев Олимжон Ортиқович -2019',
                'locale_id' => 1,
                'topic' => 'Ғарб ва шарқ адабий контекстида Амир Темур шахси талқини',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/44056',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Қобилова Наргисабегим Сулаймонбек қизи -2020',
                'locale_id' => 1,
                'topic' => 'Жек Лондон ва Абдулла Қаҳҳор ижодида бадиий психологизм',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49884',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Кадирова Наргиза Арифовна -2020',
                'locale_id' => 1,
                'topic' => 'Жаҳон адиблари ижодида эврилиш мотиви (Муштараклик ва индивидуаллик)',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49544',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Бўриева Наргиза Қўчқоровна -2020',
                'locale_id' => 1,
                'topic' => 'Шекспир сонетларининг бадиий услуби ва уни таржимада қайта тиклаш масаласи',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49346',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Рофиева Гуласал Юсубжоновна -2020',
                'locale_id' => 1,
                'topic' => 'Ўзбек тилидан француз тилига концептуал метафоралар таржимасининг ўзига хос хусусиятлари (Эркин Аъзам асарлари асосида)',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49106',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Базаров Зокир Мехриқулович -2020',
                'locale_id' => 1,
                'topic' => 'Бадиий таржимада лексик-стилистик бўёқдорликни сақлаш муаммолари (А. Қодирийнинг "Ўткан кунлар" романининг инглизча таржималари мисолида)',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49105',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];
        DB::table('dissertations')->insert($abstracts);
       //
    }
}
