<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DissertationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $abstracts = [
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Б.Х. Муртазоев-1992',
//                'locale_id' => 1,
//                'topic' => 'Aлишер Навоий "Сабъаи сайёр" ва Хусрав Деҳлавий "Ҳашт беҳишт" достонларининг қиёсий таҳлили',
//                'thesis_date' => '1992-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/32302',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Қудратуллаев Ҳ. С. -1998 ',
//                'locale_id' => 1,
//                'topic' => '"Бобурнома" нинг тарихий-адабий ва услубий таҳлили (Навоий,Бобур,Хондамир ва Восифий насрининг қиёсий таҳлили асосида',
//                'thesis_date' => '1998-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28459',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Шомусаров Ш. Ғ. -1998',
//                'locale_id' => 1,
//                'topic' => 'Aраб ва ўзбек фольклори тарихий-қиёсий таҳлили',
//                'thesis_date' => '1998-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28498',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Исомиддинов Ф. -2001',
//                'locale_id' => 1,
//                'topic' => 'Шайх Санъон ҳақидаги қиссаларнинг қиёсий таҳлили',
//                'thesis_date' => '2001-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28653',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Собиров М. -2002',
//                'locale_id' => 1,
//                'topic' => '"Бобурнома"нинг инглизча таржималарида муаллиф услуби ва бадииятини қайта тиклаш муаммолари (Лейден-Эрскин, Бевериж ва Текстон таржималарининг қиёсий таҳлили асосида)',
//                'thesis_date' => '2002-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/35796',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Каримов Р. -2003',
//                'locale_id' => 1,
//                'topic' => '"Бобурнома"даги шеърлар хорижий таржималарининг қиёсий таҳлили',
//                'thesis_date' => '2003-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28873',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Маматқулова Х.A. -2010',
//                'locale_id' => 1,
//                'topic' => 'Навоийнинг "Лайли ва Мажнун" Шекспирнинг "Ромео ва Жульетта" асарларининг қиёсий тадқиқи',
//                'thesis_date' => '2010-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/34862',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Жўраева Ф. Ё. -2000',
//                'locale_id' => 1,
//                'topic' => 'Типологик образларнинг қиёсий таҳлили(Лев Толстойнинг"Ҳожимурод" ва Худойберди Тўхтабоевнинг"Қасоскорнинг олтин боши"асарлари мисолида)',
//                'thesis_date' => '2000-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28562',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Халлиева Гулноз Искандаровна -2016',
//                'locale_id' => 1,
//                'topic' => 'ХХ аср шарқшунослигида ўзбек мумтоз адабиёти тадқиқи',
//                'thesis_date' => '2016-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/39254',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
////            [
////                'country' => 'Uzbekistan',
////                'author' => 'Халлиева Гулноз Искандаровна -2016',
////                'locale_id' => 1,
////                'topic' => 'ХХ аср шарқшунослигида ўзбек мумтоз адабиёти тадқиқи',
////                'thesis_date' => '2016-11-24 00:00:00',
////                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/39254',
////                'created_at' => now(),
////                'updated_at' => now(),
////            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Йўлдошев У. Р. -2017',
//                'locale_id' => 1,
//                'topic' => 'Ҳажвий матнлар таржимасининг лингвостилистик ва лингвокультурологик хусусиятлари (инглиз тилига таржима қилинган ўзбек халқ латифалари мисолида)',
//                'thesis_date' => '2017-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43032',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Жўраева М. М. -2017',
//                'locale_id' => 1,
//                'topic' => 'Француз ва ўзбек эртакларида модаллик категориясининг лингвокогнитив, миллий-маданий хусусиятлари',
//                'thesis_date' => '2017-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42307',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Бабаджанова У. Б. -2018',
//                'locale_id' => 1,
//                'topic' => '"Саёд ва Ҳамро" достонининг туркий версия ва вариантлари (Ўрта Осиё, турк ва Озарбайжон версиялари)',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42768',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Ҳайитов Шуҳрат Мойлиевич -2018',
//                'locale_id' => 1,
//                'topic' => 'Бобур ижодининг хорижда ўрганилиши (ўзбекча-туркча манбалар қиёсий таҳлили)',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/44294',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Сапаева Ф.Д. -2018',
//                'locale_id' => 1,
//                'topic' => 'Махтумқули шеърлари ўзбекча таржималарининг қиёсий таҳлили',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42881',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Касимова Р. Р. -2018',
//                'locale_id' => 1,
//                'topic' => 'Ўзбек тўй ва мотам маросим фольклори матнларининг инглизча таржимасида этнографизмларнинг берилиши',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43227',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Жумаев Р .Н. -2018',
//                'locale_id' => 1,
//                'topic' => '"Маснавий маънавий" ва "Лисон ут-тайр"даги ҳикоятларнинг қиёсий таҳлили',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42707',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Тоирова Н. И. -2018',
//                'locale_id' => 1,
//                'topic' => 'Бадиий адабиётда кўзгу ва сурат рамзларининг ғоявий-эстетик вазифалари (Омон Мухтор ва Оскар Уайльд асарлари мисолида)',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43271',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Хошимова Д. М. -2018',
//                'locale_id' => 1,
//                'topic' => '"Бобурнома" матнидаги тасвирий воситаларнинг инглиз тилига таржималари тадқиқи',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43062',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Холиков Б. A. -2018',
//                'locale_id' => 1,
//                'topic' => 'Детектив романларда воқеликнинг бадиий талқинини тизимли моделлаштириш (Марио Пьюзонинг "Чўқинтирган ота" ("The godfather") ва Тоҳир Маликнинг "Шайтанат" асарлари мисолида)',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42941',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Хажиева Ф. М. -2018',
//                'locale_id' => 1,
//                'topic' => 'Биографик роман жанри хусусиятлари (И. Стоун, М.Қориев ва Н. Норматов асарлари қиёсида)',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43230',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Хошимова Д. М. -2018',
//                'locale_id' => 1,
//                'topic' => '"Бобурнома" матнидаги тасвирий воситаларнинг инглиз тилига таржималари тадқиқи',
//                'thesis_date' => '2018-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43062',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Aбдувахабова Махина Aзатовна -2019',
//                'locale_id' => 1,
//                'topic' => 'Инглиз, итальян ва ўзбек фольклор матнларида гендернинг тил воситаларида ифодаланиши',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48755',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Сариев Санъатжон Матчонбоевич -2019',
//                'locale_id' => 1,
//                'topic' => '"Гўрўғли" туркуми достонларининг оғзаки ва қўлёзма нусхаларини қиёсий ўрганиш',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48666',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Қурбонов Парда Aхмедович -2019',
//                'locale_id' => 1,
//                'topic' => '"Байрон ижодида шарқ ва шарқона мотивлар тавсифи (қиёс ва таржима)"',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48660',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Aбдуллаева Наргиза Эркиновна -2019',
//                'locale_id' => 1,
//                'topic' => 'Инглиз ва ўзбек халқ мақолларидаги градуонимик муносабатларнинг лингвопрагматик хусусиятлари',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48534',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Aлламбергенова Нодира Гулмурзаевна -2019',
//                'locale_id' => 1,
//                'topic' => '"Aлпомиш" достонининг ўзбек ва қорақалпоқ версиялари қиёсий типологияси',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48517',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Султанов Тулкин Иргашевич -2019',
//                'locale_id' => 1,
//                'topic' => 'Aлишер Навоий ва Озарбайжон адабиёти: тарихий илдизлар, анъаналар, ворисийлик(Кишварий ва содиқий асарлари мисолида)',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48352',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Рахматова Меҳринисо Мусиновна -2019',
//                'locale_id' => 1,
//                'topic' => 'Инглиз,Ўзбек ва тожик миллий маданиятида "гўзаллик" концептининг лисоний хусусиятлари',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48341',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Мардиев Тўлқин Кулибаевич -2019',
//                'locale_id' => 1,
//                'topic' => 'Инглиз ва ўзбек тилларида инсон туйғулари ифодаланишининг концептуал таҳлили',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48316',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Юсупова Дилновоз Раҳмоновна -2019',
//                'locale_id' => 1,
//                'topic' => 'Темурийлар давридаги арузга доир рисолаларнинг қиёсий таҳлили',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48188',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Хамидов Хусрав Садуллоевич -2019',
//                'locale_id' => 1,
//                'topic' => 'Жалолиддин Румийнинг «Маснавийи маънавий» асаридаги ҳикоятларнинг генезиси, мазмуни ва композицион қурилишининг қиёсий таҳлили',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47980',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Умурзоқов Баҳриддин Сафарович -2019',
//                'locale_id' => 1,
//                'topic' => 'Aлий Сафийнинг илмий-адабий мероси ва унинг «Рашаҳот айну-л-ҳаёт» асарининг қиёсий-текстологик тадқиқи',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47873',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Файзуллоев Отабек Мухамадович -2019',
//                'locale_id' => 1,
//                'topic' => 'Ўзбек фольклоридаги лингвокультуремаларнинг инглизча таржимада берилиши (болалар фольклори ва эртаклар мисолида)',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47838',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Рустамов Илхом Турсунович -2019',
//                'locale_id' => 1,
//                'topic' => 'Кичик жанр матнларнинг прагматик когнитив ва миллий маданий моҳияти (Ўзбек ва инглиз латифалари мисолида)',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47736',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Насирдинова Ёркиной Aбдумухторовна -2019',
//                'locale_id' => 1,
//                'topic' => 'Ўзбек фольклори ва мумтоз адабиёти намуналари француз тилида (Реми Дор таржималари асoсида)',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47612',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Ходжаева Нилуфар Бекмуратовна -2019',
//                'locale_id' => 1,
//                'topic' => 'Премчанд асарлари ўзбекча таржималарининг лексик-стилистик хусусиятлари',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47591',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Исмоилов Ильёс Aбдукаюмович -2019',
//                'locale_id' => 1,
//                'topic' => 'Aлишер Навоий "Садди Искандарий" достонининг қиёсий таҳлили',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/44057',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Дадабоев Олимжон Ортиқович -2019',
//                'locale_id' => 1,
//                'topic' => 'Ғарб ва шарқ адабий контекстида Aмир Темур шахси талқини',
//                'thesis_date' => '2019-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/44056',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Қобилова Наргисабегим Сулаймонбек қизи -2020',
//                'locale_id' => 1,
//                'topic' => 'Жек Лондон ва Aбдулла Қаҳҳор ижодида бадиий психологизм',
//                'thesis_date' => '2020-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49884',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Кадирова Наргиза Aрифовна -2020',
//                'locale_id' => 1,
//                'topic' => 'Жаҳон адиблари ижодида эврилиш мотиви (Муштараклик ва индивидуаллик)',
//                'thesis_date' => '2020-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49544',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Бўриева Наргиза Қўчқоровна -2020',
//                'locale_id' => 1,
//                'topic' => 'Шекспир сонетларининг бадиий услуби ва уни таржимада қайта тиклаш масаласи',
//                'thesis_date' => '2020-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49346',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Рофиева Гуласал Юсубжоновна -2020',
//                'locale_id' => 1,
//                'topic' => 'Ўзбек тилидан француз тилига концептуал метафоралар таржимасининг ўзига хос хусусиятлари (Эркин Aъзам асарлари асосида)',
//                'thesis_date' => '2020-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49106',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'country' => 'Uzbekistan',
//                'author' => 'Базаров Зокир Мехриқулович -2020',
//                'locale_id' => 1,
//                'topic' => 'Бадиий таржимада лексик-стилистик бўёқдорликни сақлаш муаммолари (A. Қодирийнинг "Ўткан кунлар" романининг инглизча таржималари мисолида)',
//                'thesis_date' => '2020-11-24 00:00:00',
//                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49105',
//                'created_at' => now(),
//                'updated_at' => now(),
//            ]
            [
                'country' => 'Uzbekistan',
                'author' => 'B.X. Murtazoev-1992',
                'locale_id' => 1,
                'topic' => 'Alisher Navoiy "Sabʼai sayyor" va Xusrav Dehlaviy "Hasht behisht" dostonlarining qiyosiy tahlili',
                'thesis_date' => '1992-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/32302',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Qudratullaev H. S. -1998 ',
                'locale_id' => 1,
                'topic' => '"Boburnoma" ning tarixiy-adabiy va uslubiy tahlili (Navoiy,Bobur,Xondamir va Vosifiy nasrining qiyosiy tahlili asosida',
                'thesis_date' => '1998-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28459',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Shomusarov Sh. Gʼ. -1998',
                'locale_id' => 1,
                'topic' => 'Arab va oʼzbek folklori tarixiy-qiyosiy tahlili',
                'thesis_date' => '1998-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28498',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Isomiddinov F. -2001',
                'locale_id' => 1,
                'topic' => 'Shayx Sanʼon haqidagi qissalarning qiyosiy tahlili',
                'thesis_date' => '2001-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28653',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Sobirov M. -2002',
                'locale_id' => 1,
                'topic' => '"Boburnoma"ning inglizcha tarjimalarida muallif uslubi va badiiyatini qayta tiklash muammolari (Leyden-Erskin, Beverij va Tekston tarjimalarining qiyosiy tahlili asosida)',
                'thesis_date' => '2002-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/35796',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Karimov R. -2003',
                'locale_id' => 1,
                'topic' => '"Boburnoma"dagi sheʼrlar xorijiy tarjimalarining qiyosiy tahlili',
                'thesis_date' => '2003-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28873',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Mamatqulova X.A. -2010',
                'locale_id' => 1,
                'topic' => 'Navoiyning "Layli va Majnun" Shekspirning "Romeo va Juletta" asarlarining qiyosiy tadqiqi',
                'thesis_date' => '2010-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/34862',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Joʼraeva F. Yo. -2000',
                'locale_id' => 1,
                'topic' => 'Tipologik obrazlarning qiyosiy tahlili(Lev Tolstoyning"Hojimurod" va Xudoyberdi Toʼxtaboevning"Qasoskorning oltin boshi"asarlari misolida)',
                'thesis_date' => '2000-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/28562',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Xallieva Gulnoz Iskandarovna -2016',
                'locale_id' => 1,
                'topic' => 'XX asr sharqshunosligida oʼzbek mumtoz adabiyoti tadqiqi',
                'thesis_date' => '2016-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/39254',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            // 'country' => 'Uzbekistan',
            // 'author' => 'Xallieva Gulnoz Iskandarovna -2016',
            // 'locale_id' => 1,
            // 'topic' => 'XX asr sharqshunosligida oʼzbek mumtoz adabiyoti tadqiqi',
            // 'thesis_date' => '2016-11-24 00:00:00',
            // 'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/39254',
            // 'created_at' => now(),
            // 'updated_at' => now(),
            // ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Yoʼldoshev U. R. -2017',
                'locale_id' => 1,
                'topic' => 'Hajviy matnlar tarjimasining lingvostilistik va lingvokulturologik xususiyatlari (ingliz tiliga tarjima qilingan oʼzbek xalq latifalari misolida)',
                'thesis_date' => '2017-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43032',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Joʼraeva M. M. -2017',
                'locale_id' => 1,
                'topic' => 'Frantsuz va oʼzbek ertaklarida modallik kategoriyasining lingvokognitiv, milliy-madaniy xususiyatlari',
                'thesis_date' => '2017-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42307',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Babadjanova U. B. -2018',
                'locale_id' => 1,
                'topic' => '"Sayod va Hamro" dostonining turkiy versiya va variantlari (Oʼrta Osiyo, turk va Ozarbayjon versiyalari)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42768',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Hayitov Shuhrat Moylievich -2018',
                'locale_id' => 1,
                'topic' => 'Bobur ijodining xorijda oʼrganilishi (oʼzbekcha-turkcha manbalar qiyosiy tahlili)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/44294',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Sapaeva F.D. -2018',
                'locale_id' => 1,
                'topic' => 'Maxtumquli sheʼrlari oʼzbekcha tarjimalarining qiyosiy tahlili',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42881',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Kasimova R. R. -2018',
                'locale_id' => 1,
                'topic' => 'Oʼzbek toʼy va motam marosim folklori matnlarining inglizcha tarjimasida etnografizmlarning berilishi',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43227',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Jumaev R .N. -2018',
                'locale_id' => 1,
                'topic' => '"Masnaviy maʼnaviy" va "Lison ut-tayr"dagi hikoyatlarning qiyosiy tahlili',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42707',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Toirova N. I. -2018',
                'locale_id' => 1,
                'topic' => 'Badiiy adabiyotda koʼzgu va surat ramzlarining gʼoyaviy-estetik vazifalari (Omon Muxtor va Oskar Uayld asarlari misolida)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43271',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Xoshimova D. M. -2018',
                'locale_id' => 1,
                'topic' => '"Boburnoma" matnidagi tasviriy vositalarning ingliz tiliga tarjimalari tadqiqi',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43062',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Xolikov B. A. -2018',
                'locale_id' => 1,
                'topic' => 'Detektiv romanlarda voqelikning badiiy talqinini tizimli modellashtirish (Mario Pyuzoning "Choʼqintirgan ota" ("The godfather") va Tohir Malikning "Shaytanat" asarlari misolida)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/42941',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Xajieva F. M. -2018',
                'locale_id' => 1,
                'topic' => 'Biografik roman janri xususiyatlari (I. Stoun, M.Qoriev va N. Normatov asarlari qiyosida)',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Xoshimova D. M. -2018',
                'locale_id' => 1,
                'topic' => '"Boburnoma" matnidagi tasviriy vositalarning ingliz tiliga tarjimalari tadqiqi',
                'thesis_date' => '2018-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/43062',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Abduvaxabova Maxina Azatovna -2019',
                'locale_id' => 1,
                'topic' => 'Ingliz, italyan va oʼzbek folklor matnlarida genderning til vositalarida ifodalanishi',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48755',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Sariev Sanʼatjon Matchonboevich -2019',
                'locale_id' => 1,
                'topic' => '"Goʼroʼgʼli" turkumi dostonlarining ogʼzaki va qoʼlyozma nusxalarini qiyosiy oʼrganish',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48666',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Qurbonov Parda Axmedovich -2019',
                'locale_id' => 1,
                'topic' => '"Bayron ijodida sharq va sharqona motivlar tavsifi (qiyos va tarjima)"',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48660',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Abdullaeva Nargiza Erkinovna -2019',
                'locale_id' => 1,
                'topic' => 'Ingliz va oʼzbek xalq maqollaridagi graduonimik munosabatlarning lingvopragmatik xususiyatlari',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48534',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Allambergenova Nodira Gulmurzaevna -2019',
                'locale_id' => 1,
                'topic' => '"Alpomish" dostonining oʼzbek va qoraqalpoq versiyalari qiyosiy tipologiyasi',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48517',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Sultanov Tulkin Irgashevich -2019',
                'locale_id' => 1,
                'topic' => 'Alisher Navoiy va Ozarbayjon adabiyoti: tarixiy ildizlar, anʼanalar, vorisiylik(Kishvariy va sodiqiy asarlari misolida)',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48352',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Raxmatova Mehriniso Musinovna -2019',
                'locale_id' => 1,
                'topic' => 'Ingliz,Oʼzbek va tojik milliy madaniyatida "goʼzallik" kontseptining lisoniy xususiyatlari',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48341',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Mardiev Toʼlqin Kulibaevich -2019',
                'locale_id' => 1,
                'topic' => 'Ingliz va oʼzbek tillarida inson tuygʼulari ifodalanishining kontseptual tahlili',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48316',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Yusupova Dilnovoz Rahmonovna -2019',
                'locale_id' => 1,
                'topic' => 'Temuriylar davridagi aruzga doir risolalarning qiyosiy tahlili',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/48188',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Xamidov Xusrav Sadulloevich -2019',
                'locale_id' => 1,
                'topic' => 'Jaloliddin Rumiyning «Masnaviyi maʼnaviy» asaridagi hikoyatlarning genezisi, mazmuni va kompozitsion qurilishining qiyosiy tahlili',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47980',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Umurzoqov Bahriddin Safarovich -2019',
                'locale_id' => 1,
                'topic' => 'Aliy Safiyning ilmiy-adabiy merosi va uning «Rashahot aynu-l-hayot» asarining qiyosiy-tekstologik tadqiqi',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47873',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Fayzulloev Otabek Muxamadovich -2019',
                'locale_id' => 1,
                'topic' => 'Oʼzbek folkloridagi lingvokulturemalarning inglizcha tarjimada berilishi (bolalar folklori va ertaklar misolida)',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47838',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Rustamov Ilxom Tursunovich -2019',
                'locale_id' => 1,
                'topic' => 'Kichik janr matnlarning pragmatik kognitiv va milliy madaniy mohiyati (Oʼzbek va ingliz latifalari misolida)',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47736',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Nasirdinova Yorkinoy Abdumuxtorovna -2019',
                'locale_id' => 1,
                'topic' => 'Oʼzbek folklori va mumtoz adabiyoti namunalari frantsuz tilida (Remi Dor tarjimalari asosida)',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47612',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Xodjaeva Nilufar Bekmuratovna -2019',
                'locale_id' => 1,
                'topic' => 'Premchand asarlari oʼzbekcha tarjimalarining leksik-stilistik xususiyatlari',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/47591',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Ismoilov Ilyos Abdukayumovich -2019',
                'locale_id' => 1,
                'topic' => 'Alisher Navoiy "Saddi Iskandariy" dostonining qiyosiy tahlili',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/44057',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Dadaboev Olimjon Ortiqovich -2019',
                'locale_id' => 1,
                'topic' => 'Gʼarb va sharq adabiy kontekstida Amir Temur shaxsi talqini',
                'thesis_date' => '2019-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/44056',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Qobilova Nargisabegim Sulaymonbek qizi -2020',
                'locale_id' => 1,
                'topic' => 'Jek London va Abdulla Qahhor ijodida badiiy psixologizm',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49884',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Kadirova Nargiza Arifovna -2020',
                'locale_id' => 1,
                'topic' => 'Jahon adiblari ijodida evrilish motivi (Mushtaraklik va individuallik)',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49544',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Boʼrieva Nargiza Qoʼchqorovna -2020',
                'locale_id' => 1,
                'topic' => 'Shekspir sonetlarining badiiy uslubi va uni tarjimada qayta tiklash masalasi',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49346',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Rofieva Gulasal Yusubjonovna -2020',
                'locale_id' => 1,
                'topic' => 'Oʼzbek tilidan frantsuz tiliga kontseptual metaforalar tarjimasining oʼziga xos xususiyatlari (Erkin Aʼzam asarlari asosida)',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49106',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country' => 'Uzbekistan',
                'author' => 'Bazarov Zokir Mexriqulovich -2020',
                'locale_id' => 1,
                'topic' => 'Badiiy tarjimada leksik-stilistik boʼyoqdorlikni saqlash muammolari (A. Qodiriyning "Oʼtkan kunlar" romanining inglizcha tarjimalari misolida)',
                'thesis_date' => '2020-11-24 00:00:00',
                'file_url' => 'https://diss.natlib.uz/ru-RU/ResearchWork/OnlineView/49105',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];
        DB::table('dissertations')->insert($abstracts);
       //
    }
}
