<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResearchersArticlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $abstracts = [
//            [
//                'article_topic' => 'XORAZM MA`MUN AKADEMIYASI AXBOROTNOMASI',
//                'authors' => 'Abdullayev Ikram Iskandarovich',
//                'article_type' => "Oak",
//                'protection_year' => '2022-10/4',
//                'file_url' => 'researcher_articles/files/Mamun vak maqola.pdf',
//                'photo_url' => "researcher_articles/photos/img.png",
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
            [
                'article_topic' => 'About The Manuscript Of "Ma\'arifun Nasab" By Babajon Sanoy, The Single Copy Of Which Is Kept In The State Library Of Berlin',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna, Zohidov Rashid Fozilovich, Adambaeva Nargiza Kadambaevna',
                'article_type' => "Scopus",
                'protection_year' => '2023-7/3',
                'file_url' => 'researcher_articles/files/10796-14653-1-PB (2).pdf',
                'photo_url' => "researcher_articles/photos/img_1.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ORIENTAL LITERATURE IN THE EYES OF REYNOLD NICHOLSON',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna, Kholikov Zokhidjon Olimjonovich, Samandarov Sherzod Sultanovich',
                'article_type' => "Scopus",
                'protection_year' => '2023-6/3',
                'file_url' => 'researcher_articles/files/Article Translation 2023 scoups.pdf',
                'photo_url' => "researcher_articles/photos/img_2.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ASEAN JOURNAL ON SCIENCE & TECHNOLOGY FOR DEVELOPMENT',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna, Kholikov Zokhidjon Olimjonovich, Samandarov Sherzod Sultanovich',
                'article_type' => "Scopus",
                'protection_year' => '2023-6/3',
                'file_url' => 'researcher_articles/files/CamScanner 03-04-2023. scoups.pdf',
                'photo_url' => "researcher_articles/photos/img_3.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

//            26.03.2024 qoshilgan
            [
                'article_topic' => 'BOBOJON SАNOIYNING BERLIN DАVLАT KUTUBXONАSIDА YAGONА
NUSXАDА SАQLАNАYOTGАN “MАORIFUN NАSАB” QO‘LYOZMАSI XUSUSIDА',
                'authors' => 'Gulnoz Iskandarovna XALLIEVA, Nargiza Qadambaevna ADAMBAEVA',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/BOBOJON_SАNOIYNING_BERLIN_DАVLАT_KUTUBXONАSIDА_YAGONА_NUSXАDА_SАQLАNАYOTGАN.pdf',
                'photo_url' => "researcher_articles/photos/img_4.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Adabiyotshunoslikda davrlashtirish masalasining qiyosiy tahlili',
                'authors' => 'Xamidov Obidjon Xafizovich, Rasulov To`lqin Husenovich',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/BuxDU maqola2023.pdf',
                'photo_url' => "researcher_articles/photos/img_5.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'GLOBALLASHUV VA ADABIY JARAYONNING MUNOSABATI XUSUSIDA',
                'authors' => 'Zebo Zokirovna SABIROVA',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/GLOBALLASHUV VA ADABIY JARAYONNING MUNOSABATI XUSUSIDA (7).pdf',
                'photo_url' => "researcher_articles/photos/img_6.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'INSON VA JONZOT MIKROXRONOTOPIDA PARALLELIZM',
                'authors' => 'Bahor Bahriddinovna TO‘RАYEVА',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/INSON VA JONZOT MIKROXRONOTOPIDA PARALLELIZM.pdf',
                'photo_url' => "researcher_articles/photos/img_7.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'O`zbek adabiyotshunosligida adabiy avlod masalasining qiyosiy tahlili',
                'authors' => 'S.T.Turg`unov, SH.N.Ataxanov, O.Imonov',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/NamDU 2023 maqola.pdf',
                'photo_url' => "researcher_articles/photos/img_8.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '“CHET TIL TA’LIMIGA INNOVATSION
YONDOSHUV TAMOYILLARI VA
ILMIY-AMALIY TARJIMA
MUAMMOLARI',
                'authors' => 'Turg‘unov S.T, Ataxanov Sh.N, Mamadaliyev E. M, Tursunov A.H, Saydaliyev S, Sodiqov Z.Y, Todjihodjayev M.M, Tursunov H.B, Tursunov Z.Z',
                'article_type' => "RESPUBLIKA ILMIY-TEXNIK
ANJUMANI",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Китоб туплам.doc (2).pdf',
                'photo_url' => "researcher_articles/photos/img_9.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '',
                'authors' => '',
                'article_type' => "",
                'protection_year' => '',
                'file_url' => 'researcher_articles/files/',
                'photo_url' => "researcher_articles/photos/",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        //
        DB::table('researchers_articles')->insert($abstracts);
    }
}
