<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResearchersArticlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $abstracts = [
//            [
//                'article_topic' => 'XORAZM MA`MUN AKADEMIYASI AXBOROTNOMASI',
//                'authors' => 'Abdullayev Ikram Iskandarovich',
//                'article_type' => "Oak",
//                'protection_year' => '2022-10/4',
//                'file_url' => 'researcher_articles/files/Mamun vak maqola.pdf',
//                'photo_url' => "researcher_articles/photos/img.png",
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
            [
                'article_topic' => 'About The Manuscript Of "Ma\'arifun Nasab" By Babajon Sanoy, The Single Copy Of Which Is Kept In The State Library Of Berlin',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna, Zohidov Rashid Fozilovich, Adambaeva Nargiza Kadambaevna',
                'article_type' => "Scopus",
                'protection_year' => '2023-7/3',
                'file_url' => 'researcher_articles/files/10796-14653-1-PB (2).pdf',
                'photo_url' => "researcher_articles/photos/img_1.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ORIENTAL LITERATURE IN THE EYES OF REYNOLD NICHOLSON',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna, Kholikov Zokhidjon Olimjonovich, Samandarov Sherzod Sultanovich',
                'article_type' => "Scopus",
                'protection_year' => '2023-6/3',
                'file_url' => 'researcher_articles/files/Article Translation 2023 scoups.pdf',
                'photo_url' => "researcher_articles/photos/img_2.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ASEAN JOURNAL ON SCIENCE & TECHNOLOGY FOR DEVELOPMENT',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna, Kholikov Zokhidjon Olimjonovich, Samandarov Sherzod Sultanovich',
                'article_type' => "Scopus",
                'protection_year' => '2023-6/3',
                'file_url' => 'researcher_articles/files/CamScanner 03-04-2023. scoups.pdf',
                'photo_url' => "researcher_articles/photos/img_3.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

//            26.03.2024 qoshilgan
            [
                'article_topic' => 'BOBOJON SАNOIYNING BERLIN DАVLАT KUTUBXONАSIDА YAGONА
NUSXАDА SАQLАNАYOTGАN “MАORIFUN NАSАB” QO‘LYOZMАSI XUSUSIDА',
                'authors' => 'Gulnoz Iskandarovna XALLIEVA, Nargiza Qadambaevna ADAMBAEVA',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/BOBOJON_SАNOIYNING_BERLIN_DАVLАT_KUTUBXONАSIDА_YAGONА_NUSXАDА_SАQLАNАYOTGАN.pdf',
                'photo_url' => "researcher_articles/photos/img_4.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Adabiyotshunoslikda davrlashtirish masalasining qiyosiy tahlili',
                'authors' => 'Xamidov Obidjon Xafizovich, Rasulov To`lqin Husenovich',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/BuxDU maqola2023.pdf',
                'photo_url' => "researcher_articles/photos/img_5.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'GLOBALLASHUV VA ADABIY JARAYONNING MUNOSABATI XUSUSIDA',
                'authors' => 'Zebo Zokirovna SABIROVA',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/GLOBALLASHUV VA ADABIY JARAYONNING MUNOSABATI XUSUSIDA (7).pdf',
                'photo_url' => "researcher_articles/photos/img_6.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'INSON VA JONZOT MIKROXRONOTOPIDA PARALLELIZM',
                'authors' => 'Bahor Bahriddinovna TO‘RАYEVА',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/INSON VA JONZOT MIKROXRONOTOPIDA PARALLELIZM.pdf',
                'photo_url' => "researcher_articles/photos/img_7.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'O`zbek adabiyotshunosligida adabiy avlod masalasining qiyosiy tahlili',
                'authors' => 'S.T.Turg`unov, SH.N.Ataxanov, O.Imonov',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/NamDU 2023 maqola.pdf',
                'photo_url' => "researcher_articles/photos/img_8.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '“CHET TIL TA’LIMIGA INNOVATSION
YONDOSHUV TAMOYILLARI VA
ILMIY-AMALIY TARJIMA
MUAMMOLARI',
                'authors' => ' Г.Халлиева',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Китоб туплам.doc (2).pdf',
                'photo_url' => "researcher_articles/photos/img_9.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'THE ISSUE OF IMAGE IN FICTION LITERATURE',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/7-9 (7).pdf',
                'photo_url' => "researcher_articles/photos/img_10.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'У Ч Е Н Ы Й X X I В Е К ',
                'authors' => 'Б.Б. Тураева',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/29-30-PB (1).pdf',
                'photo_url' => "researcher_articles/photos/img_11.png",
                'locale_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '“THE STRUCTURAL ESSENCE OF THE CONCEPT “LITERARY SPACE',
                'authors' => 'Bahor TURAEVA, Dilshod NASRIDDINOV, Ulugbek KARIMOV, Dilfuza RASULMUXAMEDOVA, Makhina KUCHKAROVA',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Acceptance Letter Linguistic and Education -103520.pdf',
                'photo_url' => "researcher_articles/photos/img_12.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'SCIENTIFIC THEORETICAL FUNDAMENTALS OF COMPARATIVE ANALYSIS',
                'authors' => 'Khallieva Gulnoz Iskandarovna, Mannonova Feruzabonu Sherali qizi',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/article20230425 (3).pdf',
                'photo_url' => "researcher_articles/photos/img_13.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ARTISTIC WORD POWER',
                'authors' => 'Zebo Sabirova, Shuhratov Fozil',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Maqola impoct faktor.pdf',
                'photo_url' => "researcher_articles/photos/img_14.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'POETIC MODELS OF THE CONCEPT “LITERARY TIME”',
                'authors' => 'Bahor TURAEVA, Ulugbek KUCHIMOV',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/POETICS-S-22-00450.pdf',
                'photo_url' => "researcher_articles/photos/img_15.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Sayaka Murata as a master of psychological fiction in Japan',
                'authors' => 'Khalliyeva Gulnoz Iskandarovna, Petrosyan Naira Romanovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Sayaka Murata as a master of psychological.pdf',
                'photo_url' => "researcher_articles/photos/img_16.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'LETTER OF ACCEPTANCE',
                'authors' => 'Bahor TURAEVA, Ulugbek KUCHIMOV, Dilshod NASRIDDINOV, Zebo SABIROVA, Naira PETROSYAN',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Scoups maqola.pdf',
                'photo_url' => "researcher_articles/photos/img_17.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'The Issue Of Image In Fiction Literature',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Zebo Sabirova Zokirovna (4).pdf',
                'photo_url' => "researcher_articles/photos/img_24.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'The problem of "the individual and society" in the
context of the ideological and thematic orientation of
the I-novel "Convenience store woman"',
                'authors' => 'Prof. DSc Khalliyeva Gulnoz Iskandarovna,
Teacher Petrosyan Naira Romanovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/The problem of the individual and society .pdf',
                'photo_url' => "researcher_articles/photos/img_18.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ОБРАЗОВАНИЕ И НАУКА В XXI ВЕКЕ»',
                'authors' => ' Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/ОИНВ21ВЕКЕ. Апрель 2023. Том 4.З.Сабирова.pdf',
                'photo_url' => "researcher_articles/photos/img_19.png",
                'locale_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ОБРАЗОВАНИЕ И НАУКА В XXI ВЕКЕ»',
                'authors' => ' Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/ОИНВ21ВЕКЕ. Апрель 2023. Том 5 макола.pdf',
                'photo_url' => "researcher_articles/photos/img_20.png",
                'locale_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'GOETHE AND EASTERN POETRY: DIALOGUE OF CULTURES',
                'authors' => 'Khalliyeva Gulnoz Iskandarovna, Iskandarova Nodira Bakhrambekovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Статья Импакт-фактор.Март 2024.pdf',
                'photo_url' => "researcher_articles/photos/img_21.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'THE IDEAS OF HUMANISM IN WILLIAM FAULKNER’S WORKS',
                'authors' => 'Akramova Sitora Ikrom qizi – master’s student To`rayeva Bakhor, docent – supervisor',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/192-195 CUSR.pdf',
                'photo_url' => "researcher_articles/photos/img_22.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'THE IDEAS OF HUMANISM IN ENGLISH LITERATURE',
                'authors' => 'Akramova Sitora Ikrom qizi
master’s student
To`rayeva Bakhor
docent supervisor',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/ARIMS0608.pdf',
                'photo_url' => "researcher_articles/photos/img_23.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '«ALISHER NAVOIY VA XXI ASR»',
                'authors' => 'Shuhrat SIROJIDDINOV, Vahit TURK',
                'article_type' => "Xalqaro konferensiya",
                   'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/“ALISHER_NAVOIY_VA_XXI_ASR”_xalqaro_konferensiya_materiallari_Toshkent.pdf',
                'photo_url' => "researcher_articles/photos/img_25.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '«SHARQ-U GARB NAVOIV VA GYOTE',
                'authors' => 'Зебо СAБИРОВА, Улуғбек ҲАМДАМОВ',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Конференция_НАВОИЙ_ва_ГЁТЕ_ма#U049bола (5).pdf',
                'photo_url' => "researcher_articles/photos/img_26.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'THE CONCEPTUAL ANALYSIS OF GARDEN IN SUFI LITERATURE: GULSHANI RAZ BY MAKHMUD SHABISTARI',
                'authors' => 'Mannonova Feruzabonu Sherali kizi, Khalliyeva Gulnoz Iskandarovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Singaporian+conference+0517_230916_142018.pdf',
                'photo_url' => "researcher_articles/photos/img_27.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Gulshani roz-falsafiy didaktik asar',
                'authors' => 'Mannonova Feruzabonu Sherali qizi, Halliyeva Gulnoz Iskandarovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Uzmu xalqaro  konferensiya.pdf',
                'photo_url' => "researcher_articles/photos/img_28.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'PHYCOLOGICAL AND LITERAL ANALYSIS OF GULSHANI RAZ BY MAHKMUD SHABISTARI',
                'authors' => 'Mannonova Feruzabonu Sherali qizi',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/xalqaro IF jurnal.pdf',
                'photo_url' => "researcher_articles/photos/img_29.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'INGLIZ VA O`ZBEK RIVOYATLARIDA DINIY DARAJANING AKSIOLOGIK TAHLILI',
                'authors' => 'Mannonova Feruzabonu',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/xalqaro konferensiya. DIS1502.pdf',
                'photo_url' => "researcher_articles/photos/img_30.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'COMPARATIVE ANALYSIS OF ENGLISH AND UZBEK MYTHOLOGICAL -
NARRATIVE WORKS: HEROS AND THEMES',
                'authors' => 'Mannonova Feruzabonu Sherali qizi',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2022',
                'file_url' => 'researcher_articles/files/xalqaro konferensiya Canada.pdf',
                'photo_url' => "researcher_articles/photos/img_31.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '«СЕГОДНЯ И БУДУЩЕЕ
                                ИНДИЙСКИХ ИССЛЕДОВАНИЙ
                                В ИНДИИ И СТРАНАХ ЕВРАЗИИ»',
                'authors' => 'Qoqayeva D.M, Bokuleva B.C, Dsc Dama Devi',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Алмата, макола У.У.Мухибова.pdf',
                'photo_url' => "researcher_articles/photos/img_32.png",
                'locale_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Jurnal Hindiston',
                'authors' => 'Muhibova Ulfat Uchqunovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Мухибова У. Журнал Хиндистон.pdf',
                'photo_url' => "researcher_articles/photos/33.jpg",
                'locale_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'The Interpretation of the Gulshani Raz by M. Shabistariin the World Literature',
                'authors' => 'Khalliyeva Gulnoz Iskandarovna, Nasirov Abdurakhim Abdimutalipovich, Mannonova Feruzabonu Sherali qizi, Karimov Ulugbek Nusratovich, Adambaeva Nargiza Kadambayeva',
                'article_type' => "Journal of Propulsion Technology",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Мухибова У. Журнал Хиндистон.pdf',
                'photo_url' => "researcher_articles/photos/img_34.jpg",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'COMPARATIVE ANALYSIS OF STRUCTURE AND SEMANTICS IN ENGLISH TRANSLATIONS OF GULSHANI RAZ',
                'authors' => 'Mannonova Feruzabonu Sherali qizi, Yusupova Adolat Anvarovna',
                'article_type' => "Economy and Innovation",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Ars+Propulsion+Technology+(1).pdf',
                'photo_url' => "researcher_articles/photos/img_33.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'O`zMU xabralari',
                'authors' => 'Mannonova Feruzabonu Sherali qizi',
                'article_type' => "Mirzo Ulug`bek nomidagi O`zbekiston milliy universiteti ilmiy jurnali",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Mannonova F 4.pdf',
                'photo_url' => "researcher_articles/photos/img_36.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];


        //
        DB::table('researchers_articles')->insert($abstracts);
    }
}
