<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResearchersArticlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $abstracts = [
            [
                'article_topic' => 'About The Manuscript Of "Ma\'arifun Nasab" By Babajon Sanoy, The Single Copy Of Which Is Kept In The State Library Of Berlin',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna, Zohidov Rashid Fozilovich, Adambaeva Nargiza Kadambaevna',
                'article_type' => "Scopus",
                'protection_year' => '2023-7/3',
                'file_url' => 'researcher_articles/files/10796-14653-1-PB (2).pdf',
                'photo_url' => "researcher_articles/photos/img_1.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ORIENTAL LITERATURE IN THE EYES OF REYNOLD NICHOLSON',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna, Kholikov Zokhidjon Olimjonovich, Samandarov Sherzod Sultanovich',
                'article_type' => "Scopus",
                'protection_year' => '2023-6/3',
                'file_url' => 'researcher_articles/files/Article Translation 2023 scoups.pdf',
                'photo_url' => "researcher_articles/photos/img_2.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ASEAN JOURNAL ON SCIENCE & TECHNOLOGY FOR DEVELOPMENT',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna, Kholikov Zokhidjon Olimjonovich, Samandarov Sherzod Sultanovich',
                'article_type' => "Scopus",
                'protection_year' => '2023-6/3',
                'file_url' => 'researcher_articles/files/CamScanner 03-04-2023. scoups.pdf',
                'photo_url' => "researcher_articles/photos/img_3.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

//            26.03.2024 qoshilgan
            [
                'article_topic' => 'BOBOJON SАNOIYNING BERLIN DАVLАT KUTUBXONАSIDА YAGONА
NUSXАDА SАQLАNАYOTGАN “MАORIFUN NАSАB” QO‘LYOZMАSI XUSUSIDА',
                'authors' => 'Gulnoz Iskandarovna XALLIEVA, Nargiza Qadambaevna ADAMBAEVA',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/BOBOJON_SАNOIYNING_BERLIN_DАVLАT_KUTUBXONАSIDА_YAGONА_NUSXАDА_SАQLАNАYOTGАN.pdf',
                'photo_url' => "researcher_articles/photos/img_4.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Adabiyotshunoslikda davrlashtirish masalasining qiyosiy tahlili',
                'authors' => 'Зебо Собирова',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/BuxDU maqola2023.pdf',
                'photo_url' => "researcher_articles/photos/img_5.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'GLOBALLASHUV VA ADABIY JARAYONNING MUNOSABATI XUSUSIDA',
                'authors' => 'Zebo Zokirovna SABIROVA',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/GLOBALLASHUV VA ADABIY JARAYONNING MUNOSABATI XUSUSIDA (7).pdf',
                'photo_url' => "researcher_articles/photos/img_6.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'INSON VA JONZOT MIKROXRONOTOPIDA PARALLELIZM',
                'authors' => 'Bahor Bahriddinovna TO‘RАYEVА',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/INSON VA JONZOT MIKROXRONOTOPIDA PARALLELIZM.pdf',
                'photo_url' => "researcher_articles/photos/img_7.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'O`zbek adabiyotshunosligida adabiy avlod masalasining qiyosiy tahlili',
                'authors' => 'S.T.Turg`unov, SH.N.Ataxanov, O.Imonov',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/NamDU 2023 maqola.pdf',
                'photo_url' => "researcher_articles/photos/img_8.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '“CHET TIL TA’LIMIGA INNOVATSION
YONDOSHUV TAMOYILLARI VA
ILMIY-AMALIY TARJIMA
MUAMMOLARI',
                'authors' => 'Г.Халлиева',
                'article_type' => "OAK",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Китоб туплам.doc (2).pdf',
                'photo_url' => "researcher_articles/photos/img_9.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'THE ISSUE OF IMAGE IN FICTION LITERATURE',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/7-9 (7).pdf',
                'photo_url' => "researcher_articles/photos/img_10.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'У Ч Е Н Ы Й X X I В Е К ',
                'authors' => 'Б.Б. Тураева',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/29-30-PB (1).pdf',
                'photo_url' => "researcher_articles/photos/img_11.png",
                'locale_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '“THE STRUCTURAL ESSENCE OF THE CONCEPT “LITERARY SPACE',
                'authors' => 'Bahor TURAEVA, Dilshod NASRIDDINOV, Ulugbek KARIMOV, Dilfuza RASULMUXAMEDOVA, Makhina KUCHKAROVA',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Acceptance Letter Linguistic and Education -103520.pdf',
                'photo_url' => "researcher_articles/photos/img_12.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'SCIENTIFIC THEORETICAL FUNDAMENTALS OF COMPARATIVE ANALYSIS',
                'authors' => 'Khallieva Gulnoz Iskandarovna, Mannonova Feruzabonu Sherali qizi',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/article20230425 (3).pdf',
                'photo_url' => "researcher_articles/photos/img_13.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ARTISTIC WORD POWER',
                'authors' => 'Zebo Sabirova, Shuhratov Fozil',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Maqola impoct faktor.pdf',
                'photo_url' => "researcher_articles/photos/img_14.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'POETIC MODELS OF THE CONCEPT “LITERARY TIME”',
                'authors' => 'Bahor TURAEVA, Ulugbek KUCHIMOV',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/POETICS-S-22-00450.pdf',
                'photo_url' => "researcher_articles/photos/img_15.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Sayaka Murata as a master of psychological fiction in Japan',
                'authors' => 'Khalliyeva Gulnoz Iskandarovna, Petrosyan Naira Romanovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Sayaka Murata as a master of psychological.pdf',
                'photo_url' => "researcher_articles/photos/img_16.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'LETTER OF ACCEPTANCE',
                'authors' => 'Bahor TURAEVA, Ulugbek KUCHIMOV, Dilshod NASRIDDINOV, Zebo SABIROVA, Naira PETROSYAN',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Scoups maqola.pdf',
                'photo_url' => "researcher_articles/photos/img_17.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'The Issue Of Image In Fiction Literature',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Zebo Sabirova Zokirovna (4).pdf',
                'photo_url' => "researcher_articles/photos/img_24.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'The problem of "the individual and society" in the
context of the ideological and thematic orientation of
the I-novel "Convenience store woman"',
                'authors' => 'Prof. DSc Khalliyeva Gulnoz Iskandarovna,
Teacher Petrosyan Naira Romanovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/The problem of the individual and society .pdf',
                'photo_url' => "researcher_articles/photos/img_18.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ОБРАЗОВАНИЕ И НАУКА В XXI ВЕКЕ»',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/ОИНВ21ВЕКЕ. Апрель 2023. Том 4.З.Сабирова.pdf',
                'photo_url' => "researcher_articles/photos/img_19.png",
                'locale_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ОБРАЗОВАНИЕ И НАУКА В XXI ВЕКЕ»',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/ОИНВ21ВЕКЕ. Апрель 2023. Том 5 макола.pdf',
                'photo_url' => "researcher_articles/photos/img_20.png",
                'locale_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'GOETHE AND EASTERN POETRY: DIALOGUE OF CULTURES',
                'authors' => 'Khalliyeva Gulnoz Iskandarovna, Iskandarova Nodira Bakhrambekovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Статья Импакт-фактор.Март 2024.pdf',
                'photo_url' => "researcher_articles/photos/img_21.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'THE IDEAS OF HUMANISM IN WILLIAM FAULKNER’S WORKS',
                'authors' => 'Akramova Sitora Ikrom qizi – master’s student To`rayeva Bakhor, docent – supervisor',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/192-195 CUSR.pdf',
                'photo_url' => "researcher_articles/photos/img_22.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'THE IDEAS OF HUMANISM IN ENGLISH LITERATURE',
                'authors' => 'Akramova Sitora Ikrom qizi
master’s student
To`rayeva Bakhor
docent supervisor',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/ARIMS0608.pdf',
                'photo_url' => "researcher_articles/photos/img_23.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '«ALISHER NAVOIY VA XXI ASR»',
                'authors' => 'Shuhrat SIROJIDDINOV, Vahit TURK',
                'article_type' => "Xalqaro konferensiya",
                   'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/“ALISHER_NAVOIY_VA_XXI_ASR”_xalqaro_konferensiya_materiallari_Toshkent.pdf',
                'photo_url' => "researcher_articles/photos/img_25.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '«SHARQ-U GARB NAVOIV VA GYOTE',
                'authors' => 'Зебо СAБИРОВА, Улуғбек ҲАМДАМОВ',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Конференция_НАВОИЙ_ва_ГЁТЕ_ма#U049bола (5).pdf',
                'photo_url' => "researcher_articles/photos/img_26.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'THE CONCEPTUAL ANALYSIS OF GARDEN IN SUFI LITERATURE: GULSHANI RAZ BY MAKHMUD SHABISTARI',
                'authors' => 'Mannonova Feruzabonu Sherali kizi, Khalliyeva Gulnoz Iskandarovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Singaporian+conference+0517_230916_142018.pdf',
                'photo_url' => "researcher_articles/photos/img_27.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Gulshani roz-falsafiy didaktik asar',
                'authors' => 'Mannonova Feruzabonu Sherali qizi, Halliyeva Gulnoz Iskandarovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Uzmu xalqaro  konferensiya.pdf',
                'photo_url' => "researcher_articles/photos/img_28.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'PHYCOLOGICAL AND LITERAL ANALYSIS OF GULSHANI RAZ BY MAHKMUD SHABISTARI',
                'authors' => 'Mannonova Feruzabonu Sherali qizi',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/xalqaro IF jurnal.pdf',
                'photo_url' => "researcher_articles/photos/img_29.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'INGLIZ VA O`ZBEK RIVOYATLARIDA DINIY DARAJANING AKSIOLOGIK TAHLILI',
                'authors' => 'Mannonova Feruzabonu',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/xalqaro konferensiya. DIS1502.pdf',
                'photo_url' => "researcher_articles/photos/img_30.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'COMPARATIVE ANALYSIS OF ENGLISH AND UZBEK MYTHOLOGICAL -
NARRATIVE WORKS: HEROS AND THEMES',
                'authors' => 'Mannonova Feruzabonu Sherali qizi',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2022',
                'file_url' => 'researcher_articles/files/xalqaro konferensiya Canada.pdf',
                'photo_url' => "researcher_articles/photos/img_31.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '«СЕГОДНЯ И БУДУЩЕЕ
                                ИНДИЙСКИХ ИССЛЕДОВАНИЙ
                                В ИНДИИ И СТРАНАХ ЕВРАЗИИ»',
                'authors' => 'Qoqayeva D.M, Bokuleva B.C, Dsc Dama Devi',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Алмата, макола У.У.Мухибова.pdf',
                'photo_url' => "researcher_articles/photos/img_32.png",
                'locale_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Халкаро анжуман туплами',
                'authors' => 'Muhibova Ulfat Uchqunovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Мухибова У. Журнал Хиндистон.pdf',
                'photo_url' => "researcher_articles/photos/33.jpg",
                'locale_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'The Interpretation of the Gulshani Raz by M. Shabistariin the World Literature',
                'authors' => 'Khalliyeva Gulnoz Iskandarovna, Nasirov Abdurakhim Abdimutalipovich, Mannonova Feruzabonu Sherali qizi, Karimov Ulugbek Nusratovich, Adambaeva Nargiza Kadambayeva',
                'article_type' => "Journal of Propulsion Technology",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Мухибова У. Журнал Хиндистон.pdf',
                'photo_url' => "researcher_articles/photos/img_34.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'COMPARATIVE ANALYSIS OF STRUCTURE AND SEMANTICS IN ENGLISH TRANSLATIONS OF GULSHANI RAZ',
                'authors' => 'Mannonova Feruzabonu Sherali qizi, Yusupova Adolat Anvarovna',
                'article_type' => "Economy and Innovation",
                'protection_year' => '2023',
                'file_url' => 'researcher_articles/files/Ars+Propulsion+Technology+(1).pdf',
                'photo_url' => "researcher_articles/photos/img_33.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'O`zMU xabarlari',
                'authors' => 'Mannonova Feruzabonu Sherali qizi',
                'article_type' => "Mirzo Ulug`bek nomidagi O`zbekiston milliy universiteti ilmiy jurnali",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Mannonova F 4.pdf',
                'photo_url' => "researcher_articles/photos/img_36.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Ogahiyning asarlarida arabiy birikmalar noo\'rin qo\'llanmagan',
                'authors' => 'Yusupova Adolat Anvarovna',
                'article_type' => "Mahalliy jurnal",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/O\'zbekiston matbuot jurnali. 41-45-бетлар.pdf',
                'photo_url' => "researcher_articles/photos/img_37.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'NIKOLSONNI ILMIY IJODI DUNYO TADQIQOTCHI OLIMLAR TALQINIDA',
                'authors' => 'Yusupova Adolat Anvarovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/A.yusupova.pdf',
                'photo_url' => "researcher_articles/photos/img_38.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'IVLIN VO VA ABDULLA QAHHOR IJODIDA AVTOBIOGRAFIK HAMDA IJTIMOIY MOTIVLAR TADQIQI',
                'authors' => 'To‘rayeva Bahor Bahriddinovna',
                'article_type' => "Komporativistika jurnal",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/To‘rayeva Bahor Bahriddinovna.pdf',
                'photo_url' => "researcher_articles/photos/img_39.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'РЕТАРДАЦИЯДАН ФОЙДАЛАНИШДА МАРКАЗИЙ ОСИЁ АДИБЛАРИ УСЛУБИДАГИ ИНДИВИДУАЛЛИК ВА УНИВЕРСАЛЛИК',
                'authors' => 'To‘rayeva Bahor Bahriddinovna',
                'article_type' => "Xalqaro konferansiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/B.To\'rayeva.pdf',
                'photo_url' => "researcher_articles/photos/img_40.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'INTERNATIONAL JOURNAL OF SCIENCE AND TECHNOLOGY',
                'authors' => 'To‘rayeva Bahor Bahriddinovna',
                'article_type' => "International Scientific electronic journal",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Volume 1. Issue 7. Feb 2024 year (2).pdf',
                'photo_url' => "researcher_articles/photos/img_41.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'INTERNATIONAL JOURNAL OF SCIENCE AND TECHNOLOGY',
                'authors' => 'To‘rayeva Bahor Bahriddinovna',
                'article_type' => "International Scientific electronic journal",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Volume 1. Issue 7. Feb 2024 year (1).pdf',
                'photo_url' => "researcher_articles/photos/img_41.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'COMPARATIVE-TYPOLOGICAL STUDY OF THE PSYCHOLOGICAL
CHRONOTOPE IN THE NOVELS “THE WOMAN IN WHITE”
BY WILKIE COLLINS AND “NIGHT AND DAY” BY CHOLPON
',
                'authors' => 'To‘rayeva Bahor Bahriddinovna',
                'article_type' => "Educational Research in Universal Sciences",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/695-698.pdf',
                'photo_url' => "researcher_articles/photos/img_42.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'UNRAVELING THE PSYCHOLOGICAL CHRONOTOPE IN WILKIE
COLLINS’ “THE WOMAN IN WHITE”
',
                'authors' => 'To‘rayeva Bahor Bahriddinovna',
                'article_type' => "Educational Research in Universal Sciences",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/486-488.pdf',
                'photo_url' => "researcher_articles/photos/img_42.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'SATIRIK HIKOYALARDA BADIIY DETALLARNING AHAMIYATI',
                'authors' => 'To‘rayeva Bahor Bahriddinovna',
                'article_type' => "International Scientific-Methodological Electronic Journal ",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/SATIRIK HIKOYALARDA BADIIY DETALLARNING AHAMIYATI.pdf',
                'photo_url' => "researcher_articles/photos/img_43.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'DUNYO KOMPARATIVIST OLIMLARINING MAHMUD SHABISTARIYNING
“GULSHANI ROZ” ASARI XUSUSIDAGI TAVSIFIY-TAHLILIY QARASHLARI',
                'authors' => 'Mannonova Feruzabonu Sherali qizi',
                'article_type' => "Сomparative literature
Uzbekistan State World Languages University",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Mannonova Feruzabonu Sherali qizi.pdf',
                'photo_url' => "researcher_articles/photos/img_44.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'THE BLESSING OF WORDS
(ABOUT THE BOOK “RUHNI UYGʻOTGUVCHI SOʻZ” (“SPIRIT
AWAKENING WORD”)
BY ULUGBEK HAMDAM, LITERARY CRITIC)',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Sobirova Z. Article 10032024.pdf',
                'photo_url' => "researcher_articles/photos/img_45.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'INNOVATION IN THE MODERN
EDUCATION SYSTEM',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Zebo Sabiхалқаро.pdf',
                'photo_url' => "researcher_articles/photos/img_46.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Научный Фокус',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro jurnal",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/З.Сабирова 2024.pdf',
                'photo_url' => "researcher_articles/photos/img_47.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'MODERNIZM: O‘ZBEK SHE’RIYATI TIMSOLIDA',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Z.Sabirova konf..pdf',
                'photo_url' => "researcher_articles/photos/img_48.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'LIRIKADA POETIK OBRAZ XUSUSIDA',
                'authors' => 'Zebo Sabirova Zokirovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Sabirova Zebo Zokirovna.pdf',
                'photo_url' => "researcher_articles/photos/img_49.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'TARJIMA – QIYOSIY ADABIYOTSHUNOSLIK OBYEKTI',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Xalliyeva Gulnoz Iskandarovna (3).pdf',
                'photo_url' => "researcher_articles/photos/img_50.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'АНАЛИЗ ПЕРСОНАЖА АРТУРА БЕРТОНА В РОМАНЕ “ОВОД”',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Xalliyeva G.pdf',
                'photo_url' => "researcher_articles/photos/img_53.png",
                'locale_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ҚАДИМГИ ҲИНД ЭПОСЛАРИНИНГ
ИНДОНЕЗ ҚАДИМГИ ДАВР АДАБИЁТИГА ТАЪСИРИ',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna',
                'article_type' => "Xalqaro konferensiya",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/U.Muxibova.pdf',
                'photo_url' => "researcher_articles/photos/img_54.png",
                'locale_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'Intenational peer-reviewed journal',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna',
                'article_type' => "Scopus maqola",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Мухибова У макола.pdf',
                'photo_url' => "researcher_articles/photos/img_55.png",
                'locale_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => '“МАЪОРИФУН НАСАБ” ҚЎЛЁЗМАСИНИ ТАБДИЛ ҚИЛИШДА
ЎЗИГА ХОС ҚИЙИНЧИЛИКЛАР',
                'authors' => 'Adambaeva Nargiza Kadambaevna',
                'article_type' => "Impakt faktor",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/8..pdf',
                'photo_url' => "researcher_articles/photos/img_56.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ПАРИЖ КУТУБХОНАСИДА САҚЛАНАЁТГАН НОЁБ ХОРАЗМ
ҚЎЛЁЗМАСИ',
                'authors' => 'Adambaeva Nargiza Kadambaevna',
                'article_type' => "Impakt faktor",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/4..pdf',
                'photo_url' => "researcher_articles/photos/img_57.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'INGLIZ VA O`ZBEK TILLARIDA SOMATIK FRAZEOLOGIZMLARNING
TASNIFI',
                'authors' => 'Adambaeva Nargiza Kadambaevna',
                'article_type' => "Impakt faktor",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/148-150.pdf',
                'photo_url' => "researcher_articles/photos/img_58.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'NEMIS TILSHUNOSLIGIDA FRAZEOLOGIK BIRLIKLARNING LINGVISTIK
TADQIQI
',
                'authors' => 'Adambaeva Nargiza Kadambaevna',
                'article_type' => "Impakt faktor",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Немис тилшунослиги.pdf',
                'photo_url' => "researcher_articles/photos/img_59.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'О ЕДИНСТВЕННОМ ЭКЗЕМПЛЯРЕ РУКОПИСИ
«МАЪОРИФУН НАСАБ» БАБАДЖАНА САНОИ, ХРАНЯЩЕМСЯ
В БЕРЛИНСКОЙ ГОСУДАРСТВЕННОЙ БИБЛИОТЕКЕ
',
                'authors' => 'Adambaeva Nargiza Kadambaevna',
                'article_type' => "OAK maqolalar",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/3.pdf',
                'photo_url' => "researcher_articles/photos/img_61.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'The Interpretation of the Gulshani Raz by
M. Shabistariin the World Literature',
                'authors' => 'Adambaeva Nargiza Kadambaevna',
                'article_type' => "Scopus maqolalar",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Scopus.pdf',
                'photo_url' => "researcher_articles/photos/img_61.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'article_topic' => 'ACTUAL MATTERS OF WORLD LITERATURE AND
COMPARATIVE LITERARY STUDIES',
                'authors' => 'Xalliyeva Gulnoz Iskandarovna',
                'article_type' => "Xalqaro ilmiy-amaliy anjumani",
                'protection_year' => '2024',
                'file_url' => 'researcher_articles/files/Xoliqov Z maqola.pdf',
                'photo_url' => "researcher_articles/photos/img_62.png",
                'locale_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];


        //
        DB::table('researchers_articles')->insert($abstracts);
    }
}
